### ISSUE TITLE
Could not recognize component type LineIC message at startup

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#164]
```
I get this message at startup, its not related to latest version. 

What version of the product are you using? 3.21.0
 On what operating system? eComStation version 1.2NL (OS/2)



```

Original issue reported on code.google.com by `Joop.Nij...@gmail.com` on 1 Oct 2012 at 8:36

Attachments:
- [Could not recognize component type LineIC.jpg](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-164/comment-0/Could not recognize component type LineIC.jpg)
- [diylc-3.21.0-bugs.txt](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-164/comment-0/diylc-3.21.0-bugs.txt)
- [log-Mon Oct 01 20.50.09 CEST 2012.log](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-164/comment-0/log-Mon Oct 01 20.50.09 CEST 2012.log)

**Comment by bancika** [comment]
fixed
