### ISSUE TITLE
Auto-save question at opening program

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#166]
```
Just start the program.

After clicking away the other two issues I get this message. I always use save 
buttons from the program. So what's going wrong?

What version of the product are you using? 3.21.0
On what operating system? eComStation 1.2NL (OS/2)

```

Original issue reported on code.google.com by `Joop.Nij...@gmail.com` on 1 Oct 2012 at 8:45

Attachments:
- [auto-save question.jpg](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-166/comment-0/auto-save question.jpg)
- [diylc-3.21.0-bugs.txt](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-166/comment-0/diylc-3.21.0-bugs.txt)
- [log-Mon Oct 01 20.57.35 CEST 2012.log](https://storage.googleapis.com/google-code-attachments/diy-layout-creator/issue-166/comment-0/log-Mon Oct 01 20.57.35 CEST 2012.log)

**Comment by bancika** [comment]
improved
