### ISSUE TITLE
BOM list fail to draw with picture added.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#200]
```
What steps will reproduce the problem?
1. add shematic picture
2. do layout
3. fail to draw BOM.

What is the expected output? What do you see instead?

BOM list, FAILED TO DRAW (bottom left)

Whenever possible, please attach the latest log file. It will
provide valuable information when trying to reproduce and locate the
problem. Log files can be found in the log directory under the main
application directory and are marked with date and time.

What version of the product are you using? On what operating system?

3.7 . XP.


Please provide any additional information below.

i like to eat sausages while doing layouts..  ;)


```

Original issue reported on code.google.com by `deadastr...@yahoo.co.uk` on 15 Jan 2013 at 11:29

**Comment by ChrisOfBristol** [comment]
V3.57.0 On loading an existing file I get "Failed to draw components: Cut1 etc. Checking 56, I can see that it occurs occasionally too.
![image](https://user-images.githubusercontent.com/20310498/55737124-8b0d4e80-5a1c-11e9-96ae-10fffe2f723b.png)

**Comment by bancika** [comment]
do you have a test file? Can you please attach the latest log that contains the error?

**Comment by popout3d** [comment]
[log-2019-04-08 04.19.20.zip](https://github.com/bancika/diy-layout-creator/files/3055559/log-2019-04-08.04.19.20.zip)


[Ambisonics 3 matrix adder.zip](https://github.com/bancika/diy-layout-creator/files/3055546/Ambisonics.3.matrix.adder.zip)

**Comment by ChrisOfBristol** [comment]
Each error starts like this:
> 16:19:45,394 ERROR [AWT-EventQueue-1] DrawingManager - Error drawing Cut1
> java.lang.NullPointerException
> 	at org.diylc.components.connectivity.TraceCut.draw(TraceCut.java:96)
> 	at org.diylc.presenter.DrawingManager.drawProject(Unknown Source)
and continues for a total of 50 lines, each starting with 'at'.

**Comment by bancika** [comment]
seems to be fixed in the latest.
