### ISSUE TITLE
Amp component requests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#245]
```
What version of the product are you using? On what operating system?
3.28.0 on Windows 7

Please provide any additional information below.

After looking at the parts list & schem symbols there are a few things which 
are still needed as I build amps too:

1. Power & output transformer symbols with and without center taps.
2. Standard fuse body & symbol
3. 6.3 and 120vac volt power lights
4. RCA jacks (for reverb/tremolo), and Switchcraft jacks
5. Full wave bridge rectifier
6. IEC socket for 120VAC
7. Power resistor (5watt, 10watt, & larger)
8. Power supply filter capacitors
9. Tag strips - from 2 lugs to 8 lugs

Not trying to be a PITA or picky, just trying to help. Again, a big THANK YOU 
for everything provided for us! It's made my work better & easier for sure!
Joe


```

Original issue reported on code.google.com by `jojo...@gmail.com` on 28 Aug 2013 at 6:13

**Comment by AXington** [comment]
I know the original post is super old, but in case he sees this... to the OP:

I may take a stab at this, or at least some of these, after I finish adding Fender Mustang style slide switches. Quick question, though, which "Switchcraft jacks" are missing? Switchcraft is a brand, a standard 1/4" open jack is included. Are you looking for TRS, closed circuit, stereo, shunt... there's quite a few to do, though they could be represented pretty easily, likely, with the same drawing, but could add properties or values if you are relying on this to generate your BOM.

For bridge rectifiers, I'm familiar with a lot of preamp schematics and work, but not power amp, when used in guitar amps, which type is typically used more often, 4 in a line, or the 'table' style with 4 legs. I assume you're gonna be laying this out on a PCB, I guess I could add both. 

As for the resistor and filter caps, there's about half a billion (exaggeration, I know) types, sizes, values, etc used in amps, I'll start with some of the more common ones, the ones that I'll probably be personally using in my next amp project, and add more as needed.

**Comment by bancika** [comment]
added all
