### ISSUE TITLE
TO-92 (and other) outlines should have draggable wire connection points

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#250]
```
For TO-92 transistors and other components with flexible wire leads, the end of 
each of the three wires needs to be able to be dragged individually to any grid 
position, i.e. any hole in the board.

At present, using a TO-92 package on stripboard requires that the pins are 
evenly spaced and in a line. In a practical layout this may not be appropriate.

diylc 3.28.0 on Windows 7 64-bit jre7 version 1.7.0_21
```

Original issue reported on code.google.com by `KrisBlu...@gmail.com` on 24 Sep 2013 at 11:49

**Comment by bancika** [comment]
Using the new building blocks feature it's possible to combine TO-92 transistor and 3 wires to accomplish this.

**Comment by Juncus** [comment]
Using blocks could be a solution but for the fact that the middle pin is not actually a linkable item. It is therefore impossible, it appears to even make a block that would work. As they are fundamental objects the inability to use them in a circuit design does limit this software to an extremely narrow set of projects. I only started using the program today and had not got round to placing the NPN's. So now I guess, as in 4 years the issue has not been resolved, it is unlikely to ever happen.

**Comment by Juncus** [comment]
Ah yes I tried that just as the manual suggests. That's when I found the wires could not be attached and behave as fixed points just like the original points on the TO92.

**Comment by bancika** [comment]
Circuits without transistors? What are you talking about? :) I drew dozens of layouts with TO92 resistors without issues.

Why would you want to label building block that consists of a transistor and 3 wires? The transistor itself has a name and that will appear on the BOM. The 3 wires are not important for the BOM.
