### ISSUE TITLE
Blank menu lines

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bancika/diy-layout-creator#254]
```
When I use the Config menu option, only the un-ticked options show a 
description, the ticked ones are blank, but if I hover over a ticked option the 
description shows. This is a recent problem. Perhaps the text colour is the 
same the background colour?

Version 3.28.0 from GetDeb repository on Linux Mint-16 (Petra) Cinnamon.


```

Original issue reported on code.google.com by `ChrisofB...@gmail.com` on 16 Dec 2013 at 6:21

**Comment by ChrisOfBristol** [comment]
This continues in V3.37 on Linux Mint 18.1 with openjdk8-8-jre.

**Comment by bancika** [comment]
did you try this https://azizsaboor.wordpress.com/2015/03/17/fixing-netbeans-menu-display-on-linux-missing-menu-borders-white-on-white-invisible-menu-items/

**Comment by ChrisOfBristol** [comment]
I have, but it makes no difference.

**Comment by bancika** [comment]
interesting. It has to do with mint distribution. I have installed debian to try and works fine.

**Comment by ChrisOfBristol** [comment]
Could be, I have switched from Mint to Ubuntu MATE and back to Mint, so 
that's quite likely. I'm using Cinnamon which is less solid than MATE so 
may be the cause of the problem.

I have attached Debreate, it's an easy way of creating a .deb file and 
will run on Debian.
Chris
