### ISSUE TITLE
Can't open DIYLC 3.28.0 OSX  on 10.7.5 - Java version 8 update 71

### ISSUE THREAD

**Issue by ilcaccillo** [bancika/diy-layout-creator#273]
Hello,
I unzip diylc-3.28.0-osx.zip and then click on the "DIYLC" file and it doesn't open, nothing happens at all.
Right click and Open also has the same result.

I already had the setting "Allow Applications Downloaded From" set for "Anywhere"

I'm able to open DIYLC version 2

I'm able to open DIYLC 3.28.0 (multi-platform) although I have to use the "diylc.far" file,  I dont know how to use or open the run.sh

The problem happens also with other different V3 releases for MAC

I'm running OSX 10.7.5 and have Java 8 update 71 instaled

Thanks
Best regards

**Comment by bancika** [comment]
Is this still an issue with 3.38?
Thanks and sorry for not responding earlier.

**Comment by Modbuss** [comment]
Yes it is still an issue with 3.38, just tried downloading and installing and get a message saying "DIYLC is damaged and cant be opened and should be moved to the trash."

**Comment by bancika** [comment]
Did you enable 3rd party apps. Ironically, OSX is the one that damages the app by disabling it and then it complains about it :)

I have verified that app works fine under OSX if java 6 is present and 3rd party apps enabled

**Comment by Modbuss** [comment]
Yep I got it to work now, pretty dumb on OSX's part if you ask me. Works great now! Thanks!!

**Comment by bancika** [comment]
thanks, closing
