### ISSUE TITLE
Unable to rotate vacuum tubes

### ISSUE THREAD

**Issue by ssapp72** [bancika/diy-layout-creator#274]
I'm unable to rotate triodes and pentodes.  I verified that I am able to rotate resistors, capacitors, potentiometers, and several other parts, so it seems to just be the tubes that won't rotate.  

Could you include a beam power pentode symbol and show a little love for the 6V6 guys out there? :)  

Thanks for the great software!  It's a pleasure to use.

**Comment by bancika** [comment]
will do, thanks

**Comment by bancika** [comment]
hmm, did you try do deselect "suppressor grid" box in the properties dialog? I think that will give you the right symbol for 6v6, no?

**Comment by bancika** [comment]
tube rotation is added, will include in the next release.
