### ISSUE TITLE
DIYLC Damaged?

### ISSUE THREAD

**Issue by bnilsson11** [bancika/diy-layout-creator#277]
After downloading DIYLC, my Mac says "DIYLC 10.33.29 is damaged and cannot be opened. It should be moved to the Trash."

I am using OS X 10.11.5.

**Comment by bancika** [comment]
you need to allow 3rd party apps

**Comment by alixanc** [comment]
since sierra doesn't have a option to "allow 3rd party apps" in the gui, you have to use this command: 
sudo spctl --master-disable
for more information hit http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/
