### ISSUE TITLE
Chinese can provide language support

### ISSUE THREAD

**Issue by guoqingaa** [bancika/diy-layout-creator#279]
Chinese can provide language support
Or provide multi language plug-in settings, allowing users to modify the software display text multi language

能否提供中文语言支持
或者提供多语言外挂设置，让用户可以修改软件的显示文字的多国语言

**Comment by bancika** [comment]
#

**Comment by bancika** [comment]
Hi, I added support for internationalization. Do you wish to participate and translate a file?
Thanks!
