### ISSUE TITLE
blank saved projects

### ISSUE THREAD

**Issue by mbwhite81** [bancika/diy-layout-creator#282]
Hi,

version 3.34 on Mac OsX 10.12.
I work on a project, and save it. When I re-open the file the project is blank.

Thanks

**Comment by bancika** [comment]
can you please upload the app log from logs folder from the time that happened?

**Comment by mbwhite81** [comment]
hi, I've attached the zip file to this message

best




[log.zip](https://github.com/bancika/diy-layout-creator/files/685405/log.zip)

**Comment by bancika** [comment]
nothing suspicious in the logs, can you please make a diy file that opens empty and send that to me so I can analyze it? Maybe it has something that prevents DIYLC from reading it.

**Comment by mbwhite81** [comment]
I have one that I've tried again to save, just 20 minutes ago.
I'm pasting the logs as well.
[log.zip](https://github.com/bancika/diy-layout-creator/files/690376/log.zip)
[cj11_layout.diy.zip](https://github.com/bancika/diy-layout-creator/files/690377/cj11_layout.diy.zip)

**Comment by mbwhite81** [comment]
I've just downloaded the new version 35.0.
Same issue

**Comment by bancika** [comment]
it opens with one eyelet board on the top of the drawing. There's nothing shown when it opens, but when I scroll up there's a board. Is that what you drew?

**Comment by mbwhite81** [comment]
I don't remember. Maybe. I've tried so many times that yes, it could be right.
So, is it an issue with my mac?

**Comment by bancika** [comment]
Hmm, if that's what you drew, I don't see an issue. There's one component and it opens properly. When you open the file can you scroll up to see the component? Try clicking the tiny button in the bottom-right corner, it will show a thumbnail of the whole project and you can see what's there are scroll easily.

**Comment by mbwhite81** [comment]
yes, I zoomed out the entire project, but there's nothing in it.

**Comment by bancika** [comment]
I managed to get a mac (sierra) to try this, but your project file opens nicely. Here's what I see when it opens (after scrolling all the way to the top)
![diylc-osx](https://cloud.githubusercontent.com/assets/11462281/25770448/d4ae0c52-3235-11e7-8f69-88abfe0f9058.PNG)
