### ISSUE TITLE
If the folder name contains åäö, files aren't found [linux]

### ISSUE THREAD

**Issue by loidor** [bancika/diy-layout-creator#283]
So, I'm working on a Swedish system, meaning my Downloads folder is called "Hämtningar". If I run it from there, I get:

java.io.FileNotFoundException: /home/loidor/H%c3%a4mtningar/lib/diylc-core.jar (Filen eller katalogen finns inte)

In other words, The file or directory doesn't exist.

**Comment by bancika** [comment]
Tested under ubuntu, this should be working fine in 3.38, please verify.

**Comment by loidor** [comment]
It works perfectly now. Thanks!
