### ISSUE TITLE
Jumper with length 0 not selectable

### ISSUE THREAD

**Issue by martijnpot52** [bancika/diy-layout-creator#286]
A Jumper with length zero is not selectable. It can therefore not be moved nor deleted. If other object coincide with it, they cannot be moved any more.

Workaround:
Open .diy file and search for a Jumper that has the same coordinates  for the two end points. Change one coordinate to get a non-zero length and you can select it again (after opening in diylc). Don't delete the Jumper entry in the .diy file as this can screw up the references. I've been there...

Example:
[JumperWithoutLengthBug.txt](https://github.com/bancika/diy-layout-creator/files/709501/JumperWithoutLengthBug.txt)
Rename this file extension to .diy as githup does not support .diy files.

**Comment by bancika** [comment]
fixed for v38
