### ISSUE TITLE
Program says app was not closed normally

### ISSUE THREAD

**Issue by GeeTeeCee** [bancika/diy-layout-creator#297]
Even though I do frequent Saves during editing and always say Yes to save changes upon Exit, when I reopen the file I keep getting a message saying, "It appears that aplication was not closed normally ... "
 
![open msg](https://cloud.githubusercontent.com/assets/28534363/25805266/894ecda0-3442-11e7-996d-233294c1e5ad.jpg)

[Using version 3.40 on XP-Pro]

PS: You might like to fix the spelling of 'application' in that message. :-)

**Comment by bancika** [comment]
did it happen only once or every time?

**Comment by GeeTeeCee** [comment]
It happened numerous times yesterday when I first installed the application, but doesn't happen today.

Very strange.

**Comment by bancika** [comment]
I found a scenario that causes this when running multiple instances of the app at the same time. Was that the case?

**Comment by GeeTeeCee** [comment]
Possibly. I was trying out its functionality, so I may have had two instances running without realizing it.

**Comment by bancika** [comment]
ok, I fixed that for next version
tnx
