### ISSUE TITLE
Request: ability to lasso objects for grouping

### ISSUE THREAD

**Issue by GeeTeeCee** [bancika/diy-layout-creator#298]
This may be difficult to accomplish in code, but it would be fantastic if, instead of having to click each object separately whilst holding down the CTRL key, we could put a frame around a bunch of objects and then CTRL-G them in order to group them for moving purposes.

**Comment by bancika** [comment]
well, you can do it :)

**Comment by GeeTeeCee** [comment]
What do you mean?

**Comment by bancika** [comment]
you can click and drag the mouse around objects you want to select, then press Ctrl+G and voila!

**Comment by GeeTeeCee** [comment]
Okay, when I try that it frames the whole board initially and is very difficult to get the lasso to reduce without moving every object on the board.

**Comment by bancika** [comment]
I see. Then I can make right click make the lasso rectangle without moving any components. You'd be able to select stuff inside a large board without moving the board. Sounds good?

**Comment by GeeTeeCee** [comment]
I'm thinking it would start as a cross hairs at the point where the click is done, then expand (in both X and Y directions) by dragging until un-clicked.. 

Microsoft Paint's select function is what I have in mind.

**Comment by bancika** [comment]
I see what you mean, that's not very easy to do here. Paint is raster-based software and DIYLC is vector, like corel. It works differently. I think that right click to select without moving any components will suffice for this use case.

**Comment by GeeTeeCee** [comment]
Whatever you can achieve in the environment will be appreciated. Thanks.

**Comment by bancika** [comment]
Ok, this will be included in 3.41
