### ISSUE TITLE
JRE Problem

### ISSUE THREAD

**Issue by Sylv1v** [bancika/diy-layout-creator#300]
Hello (from France),
I am trying to install DIY layout creator. After installation, when it tries to run, a window pops up saying : 
"The registry refers to a nonexistent Java Runtime Environment installation or the runtime is corrupted".
I run Windows 10 64bits built 1607 with the latest JRE package.
Any ideas on what to do to make it work?

Thanks!
Sylvain

**Comment by bancika** [comment]
can you try to open this link and verify that java is installed properly

https://www.java.com/en/download/installed.jsp

**Comment by Sylv1v** [comment]
Thank you for your prompt answer!
It says : you have the recommended java installed (version 8 update 131) on firefox.
It won't work on Chrome and MS Edge as java is desactivated.

**Comment by bancika** [comment]
odd. Is your java 32 bit or 64 bit? What happens if you type "java -version" in the console?

**Comment by tomlut** [comment]
Same issue. 32 bit Java (v8 build 131) Windows 10 Pro 64 bit.

**Comment by bancika** [comment]
I think you need 64 bit java

**Comment by tomlut** [comment]
I'm not using a 64bit web browser so I'm never given that option. Also DIYLC used to work with the 32 bit version.

**Comment by tomlut** [comment]
Found the 64 bit version on the manual download page. Installed and DIYLC is now running. Thanks for your assistance.

**Comment by bancika** [comment]
Glad it works now. It's something about JRE, doesn't sound like it's DIYLC-related issue. Closing for now.
Cheers
