### ISSUE TITLE
Resistors Value does not center

### ISSUE THREAD

**Issue by animalejo** [bancika/diy-layout-creator#301]
This a stupid problem but it's got my nerves
the resistors values don't stay on center

screenshot:
[https://lh3.googleusercontent.com/perQU7L-nau02BP-Df8bzcUtmPS9IZWyuvhs4kOA-vZ22EZq36wiKKpCZQthDnO-fV0XenQrTGidx3U=w1920-h947](url)

**Comment by bancika** [comment]
yes, seems to be a regression bug, it's not by design.

**Comment by bancika** [comment]
fixed for 3.41
