### ISSUE TITLE
OSX Recent file submenu

### ISSUE THREAD

**Issue by aphilip** [bancika/diy-layout-creator#303]
On OSX Sierra when I hover over the recent file menu it opens a second version of the whole file menu in the main window. This issue is not present with other sub menus.
The second menu dissappears when I click the main canvas

https://drive.google.com/open?id=0BwFILELXFvUbX2FjOEx3ZWpLbjQ

**Comment by bancika** [comment]
Seems like a java bug on mac. I'll try to change the mechanism I use for that submenu and see if it helps in the next version

**Comment by bancika** [comment]
Can anyone please try the latest release and see if it makes an improvement? It should
