### ISSUE TITLE
Left mouse click on a component has no effects

### ISSUE THREAD

**Issue by mmihalj** [bancika/diy-layout-creator#305]
Selecting of components appear to be difficult. Left mouse click on a component has no effects sometimes.

**Comment by bancika** [comment]
can you provide more information?  Hard to figure out what's going.

Where are you clicking? Component tree or canvas? Can you reproduce it? Which OS? Can you attach logs?

**Comment by mmihalj** [comment]
It is happening all the time since last update. 
This occurs on canvas. 
OS is Windows 10. I am not sure if logs are created, since there is no error. Happy to send logs otherwise just not sure how...

**Comment by bancika** [comment]
fixed
