### ISSUE TITLE
Selection sizes are now nonsense

### ISSUE THREAD

**Issue by pmfawcett** [bancika/diy-layout-creator#306]
The selection size feature (button in lower right hand corner) now seems to be returning nonsense values in 3.40.0. This makes it extremely difficult to appropriately resize trace pngs in third party software.

**Comment by gtranter** [comment]
The values are being scaled with the zoom factor. Not sure if that is the only problem.

**Comment by pmfawcett** [comment]
Scaling with the zoom factor is obviously not the desired behaviour.

**Comment by EL34xyz** [comment]
The selection size tool only measures correctly at 100% zoom.
Other zoom levels returns wrong size info

Can we push this fix up into the next release please?

**Comment by bancika** [comment]
Included for 3.42.0

**Comment by EL34xyz** [comment]
Thanks bancika
