### ISSUE TITLE
Fill in holes in Marshall style perf board

### ISSUE THREAD

**Issue by Citysmasher** [bancika/diy-layout-creator#311]
Is it possible to fill in holes in the Marshall style board after the design is complete?

**Comment by bancika** [comment]
I do not agree with this request. This component represents board like shown below. It comes with the holes. If you were to use it to build an amp, you wouldn't go back and fill in the unused holes after you are done wiring, right?

There's blank board that can be configured to have the same color as marshall-style board and then you can use it to place eyeley/turret components wherever you want. You can use project grid as a guideline where to put them.

<img src="http://www.kurtsequipment.com/reproboards/jtm50.jpg"/>

**Comment by Citysmasher** [comment]
The reason you use this board other than the look is for the grid to hole spacing.  Especially when designing from scratch.  You need the fixed hole spacing (assigned globally) so you can lay the board out and you are not sure what it looks like until you are done.  It would be nice to simply eliminate the unused holes after before sending the file to CNC board drilling.  Instead you have to choose to not have a fixed hole spacing (unless you do it completely manually using the blank board and then you can't change the spacing globally) or you end up with a bunch of extra holes at the end when you are done.
