### ISSUE TITLE
电阻参数设置存在BUG

### ISSUE THREAD

**Issue by widelee88** [bancika/diy-layout-creator#316]
软件作者，您好！
首先特别感谢您写的这个DIYLC软件，给我DIY制作带来了很大很大的帮助，特再次感谢您的辛苦编写！
然而，最近在使用3V40版本中，发现一个小问题。
通常情况下，在元器件参数页面中，选中右边的小方框，点击确定。之后，紧接着放置同类元器件的时候，会把上一次修改的参数再次应用到。然而，在电阻参数设置页面中，右边的小方框，选中之后，再次放置电阻，没有按照上一次改动的设置参数来，而是依然按照默认参数。这就说明，电阻参数设置页面存在BUG。
希望您在百忙之后可以修正这个问题。
不甚感激与感谢！
一个中国大陆使用者。

**Comment by bancika** [comment]
tested and it works as expected. Only when you tick the box on the right does a parameter value gets saved as default
