### ISSUE TITLE
Copper track width

### ISSUE THREAD

**Issue by robs81** [bancika/diy-layout-creator#319]
Copper tracks look (and print) fatter in v40 vs v38... My project is drawn in v38, I cannot continue it with v40. I use OSX version on 10.6.8.

I love your soft!
v38:
![v38](https://user-images.githubusercontent.com/29666899/27501928-ba2ad854-5870-11e7-98b8-47c808b3fc05.png)
v40:
![v40](https://user-images.githubusercontent.com/29666899/27501927-ba2622aa-5870-11e7-96fa-d087373e5d4e.png)

**Comment by bancika** [comment]
older versions used to round up/down copper trace sizes but it was causing them to be notoriously imprecise. I suggest switching to v40 and adjusting trace sizes to the actual width you need. It should be 100% true in v40.
