### ISSUE TITLE
High DPI issues

### ISSUE THREAD

**Issue by guiweber** [bancika/diy-layout-creator#325]
The following issues were noted when running the app on a 220 DPI screen (15" at 4K resolution), both Windows (tested under W10) and Linux (tested under Fedora with Gnome Wayland) are affected. I am using the default DPI scaling of 200% under Linux and 250% under Windows.

- The rulers are very small and the numbers are not legible.
- The component menu is not large enough to display all component names and cannot be resized.
- The folder rows in the component menu are not tall enough and the text is truncated. Only the folders are affected, the components themselves seem to have taller rows and look fine.
- The icons are very small, such as the search icon, the 4 icons at the bottom right of the screen, the auto-scroll icon and all other icons in the menus.
- The rows in the BOM windows are not tall enough which makes the text illegible.

![capture1](https://user-images.githubusercontent.com/7825368/28220326-0932f400-688d-11e7-99a5-6200901444e3.PNG)
![capture2](https://user-images.githubusercontent.com/7825368/28220330-0aeab1c0-688d-11e7-86ba-74857f2822cd.PNG)

**Comment by guiweber** [comment]
P.S. The About windows is also too small for its content.

![capture3](https://user-images.githubusercontent.com/7825368/28220536-dede050e-688d-11e7-994a-2a78cd40706a.PNG)

**Comment by bancika** [comment]
Found this solution, please check if it works https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display

> Just found an easy solution on my Windows 10 machine:

> Find java.exe you installed.
> Right click -> Properties
> Go to Compatibility tab
> Check Override high DPI scaling behavior.
> Choose System for Scaling performed by:

**Comment by rickmccl** [comment]
Following your suggestion, this seems to be working for me: 

Find C:\Program Files (x86)\DIYLC\diylc.exe
 (same steps as above)
Right click -> Properties
Go to Compatibility tab
Check "Override high DPI scaling behavior" box.
for "Scaling performed by:" choose "System (Enhanced)"

Thanks!


![image](https://user-images.githubusercontent.com/46308562/50580184-9a776d00-0e19-11e9-940d-c170e956a79c.png)

**Comment by maeknight** [comment]
this is still an issue under linux, and the suggested solutions do not work

![image](https://github.com/bancika/diy-layout-creator/assets/130556032/74c93c13-12bb-48ba-a46f-e04c68b7e1c9)
