### ISSUE TITLE
OSX tells me latest release is broken :(

### ISSUE THREAD

**Issue by hedefalk** [bancika/diy-layout-creator#327]
![image](https://user-images.githubusercontent.com/116520/29934132-574dcb16-8e7a-11e7-9416-3a6fd9b7a2cd.png)

**Comment by bancika** [comment]
OSX is idiotic :)

you need to enable 3rd party apps.

**Comment by hedefalk** [comment]
Sorry, I totally agree, hate that gatekeeper crap and I don't ever use the app store, but normally I would get a question and I can go in there and override temporarily but persisting for that app but cannot this time, I guess since not native app but Java? 

![image](https://user-images.githubusercontent.com/116520/29935510-49d64378-8e7f-11e7-9557-3e98d3ccbf26.png)

Anyway:

sudo spctl --master-disable
restart settings and then:

![image](https://user-images.githubusercontent.com/116520/29935529-57712336-8e7f-11e7-9fb8-c14b05d0d30a.png)

Maybe this was in instructions, but I missed it. Thx!

**Comment by bancika** [comment]
yup, mentioned on the front page
https://github.com/bancika/diy-layout-creator
