### ISSUE TITLE
Setting negative border thickness makes the object disappear

### ISSUE THREAD

**Issue by danholland** [bancika/diy-layout-creator#333]
If you set the border thickness of an object to a negative number the object cannot be drawn and you receive error "Failed to draw components: <component name>" in the status bar. You are then unable to select the object to delete/change the border back.
Not a major issue (border can be reset by just editing the file) but might be worth validating the border thickness input.

Really nice piece of software, by the way. It's been very useful. Your effort is much appreciated.

**Comment by bancika** [comment]
added validation
