### ISSUE TITLE
Auto-Save and Close File 

### ISSUE THREAD

**Issue by JdaleH** [bancika/diy-layout-creator#334]
After saving file and exiting program, re-opening program gives Auto-Save statement to the effect that the program wasn't closed properly and offers to open the last saved version of project.  File show presence of autoSave.diy.  Could you add a "close" function that would close the file, but leave the program open for viewing next file?

**Comment by bancika** [comment]
Redone how auto-save works and now it keeps the history of edited files with the maximum backup folder size. Will be released in 3.57
