### ISSUE TITLE
(MacOS) Right-click on component to open menu has unexpected behavior

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#336]
DUT: MacBook Air 2012
OS: MacOS High Sierra
Version: v3.40.0 

Repro:
1. Select a component to highlight it
2. Right-click to access right-click menu

Expected Results:
3. The component should not be de-selected
4. "Save as Variant" option should be available

Actual Results:
3. The component gets de-selected
4. I cannot save the component as a variant, the item on the menu is grayed out

Issue does not reproduce on Windows version

**Comment by bancika** [comment]
fixed for the next version
