### ISSUE TITLE
(MacOS) Cannot save or load variants

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#337]
DUT: MacBook Air 2012
OS: MacOS High Sierra
Version: v3.40.0 

Reproduction:
1. Add a new component to a new or existing project
2. Edit the component properties or appearance (right-click > Edit Selection), e.g., change its width, and then click "OK" to apply changes
3. Right-click the component again and select "Save as Variant" and give the variant a name, e.g., "MyVariant"
4. Create another component of the same type as in #1 above - it should be the default variant
5. Right-click the new component (from #4), scroll over the "Apply Variant" submenu

Expected Result:
6. MyVariant appears in the variant submenu

Actual Result:
6. Nothing appears in the variant submenu

Issue does not reproduce in Windows version.

**Comment by MacFly77** [comment]
Same problem here on OSX El Capitain 10.11.6

**Comment by stevensloane** [comment]
Still an issue on both my Macs

**Comment by bancika** [comment]
fixed for the next version

**Comment by stevensloane** [comment]
Awesome!

**Comment by MacFly77** [comment]
Great!

**Comment by iiimonfiiire** [comment]
Verified fixed in v3.45
