### ISSUE TITLE
(MacOS, Win) Copy+paste several components automatically groups the new copies

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#338]
OS: MacOS High Sierra, Windows 10
Version: v3.40.0 

Reproduction:
1. Select 2 or more components in a project
2. Edit > Copy (or CTRL + C)
3. Edit > Paste (or CTRL + V)
4. Place the newly created set of components somewhere on the canvas, and then click somewhere else on the background to de-select these components
5. Click again on one of the new components to highlight it

Note that this highlights all of the recently created components from #4, and not just the single component from #5 as desired. You have to Ungroup (CTRL + U) these components beforehand if you want to work with only one of them at a time.

**Comment by bancika** [comment]
added for 3.46.0
