### ISSUE TITLE
(Win) Components do not load in toolbox if master directory begins with non-alphanumeric char

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#339]
OS: Windows 10
Version: v3.40.0 

Reproduction: 
1. Download new version as .ZIP
2. Extract archive
3. Retitle the program's master directory name from "diylc-3.40.0" to something that begins with a non-alphanumeric character such as "!diylc-3.40.0" or "~diylc-3.40.0"
4. Execute diylc.exe
5. Note that the components are now **missing** from the toolbox on the left-hand side.
6. Quit the program
7. Retitle the master directory to "diylc-3.40.0" 
8. Execute diylc.exe again
9. Components appear again in the toolbox

**Comment by bancika** [comment]
fixed for 3.53
