### ISSUE TITLE
Highlight connected traces on pcb/vero

### ISSUE THREAD

**Issue by starpath07** [bancika/diy-layout-creator#344]
please consider the possible inclusion of a "path" tool, mostly in the strip- and printed circuit board mode in which whenever you click on a particular pcb track or stripboard conductor, it highlights the whole connected length clicked upon so that it would be easy to check for missing and/or misplaced cuts and/or copper strip bridging jumpers in stripboard mode or misrouting in pcb mode. This would help very much during board designing. Thanks and well done.

**Comment by iiimonfiiire** [comment]
+1. This is a great idea. I've been doing this manually while creating vero layouts by adding different colored traces to the board. This feature would be a huge time-saver.

**Comment by bancika** [comment]
done for 3.42.0
