### ISSUE TITLE
Export PDF Java issue

### ISSUE THREAD

**Issue by animalejo** [bancika/diy-layout-creator#345]
This message appears to me when I try to export to PDF, before I didn't have this problem and now out of nowhere it shows me that error :(

https://www.dropbox.com/s/x0bzt17zcjubmm5/pdfjavaproblem.jpg?dl=0

**Comment by bancika** [comment]
Can you please upload the latest log file? It should be here C:\Users\<your user>\.diylc\logs

**Comment by animalejo** [comment]
this is the last log file:

> 00:53:33,053 DEBUG [main] DIYLCStarter - Java version: 1.8.0_161-b12 by Oracle Corporation
> 00:53:33,053 DEBUG [main] DIYLCStarter - OS: Windows 10 10.0
> 00:53:33,053  INFO [main] DIYLCStarter - Starting DIYLC with working directory C:\Program Files (x86)\DIYLC
> 00:53:33,340  INFO [main] ConfigurationManager - Initializing configuration
> 00:53:33,459  INFO [main] Presenter - installPlugin(ToolBox)
> 00:53:33,533  INFO [main] Presenter - Loading component types.
> 00:53:34,659 DEBUG [main] Presenter - Guitar: [Single Coil Pickup, P-90 Single Coil Pickup, Humbucker Pickup, LP Switch, Lever Switch]
> 00:53:34,665 DEBUG [main] Presenter - Semiconductors: [SIP IC, Transistor (TO-3 package), Transistor (TO-1 package), Diode (plastic), Transistor (TO-220 package), LED, Diode (glass), DIP IC, Transistor (TO-92 package)]
> 00:53:34,665 DEBUG [main] Presenter - Boards: [Marshall Style Perf Board, Terminal Strip, Vero Board, Blank Board, TriPad Board, Perf Board w/ Pads, Eyelet Board, Breadboard]
> 00:53:34,665 DEBUG [main] Presenter - Passive: [Film Capacitor (radial), Electrolytic Capacitor (radial), Ceramic Capacitor (radial), Potentiometer, Electrolytic Capacitor (axial), Trimmer Potentiometer, Resistor, Film Capacitor (axial)]
> 00:53:34,665 DEBUG [main] Presenter - Schematics: [Battery (symbol), JFET (symbol), Triode (symbol), Transformer Core (symbol), Resistor (symbol), MOSFET (symbol), IC (symbol), Diode (symbol), LED (symbol), Diode (symbol), Inductor (symbol), BJT (symbol), Ground (symbol), Schottky Siode (symbol), Capacitor (symbol), Zener Diode (symbol), Transformer Coil (symbol), Pentode (symbol), Potentiometer (symbol)]
> 00:53:34,666 DEBUG [main] Presenter - Electromechanical: [Closed 1/4" Jack, Mini Toggle Switch, Cliff 1/4" Jack, Mini Relay, 9V Battery Snap, Plastic DC Jack, Open 1/4" Jack]
> 00:53:34,666 DEBUG [main] Presenter - Misc: [Bill of Materials, Label, PCB Text, Image]
> 00:53:34,666 DEBUG [main] Presenter - Connectivity: [Dot, Jumper, Copper Trace, Trace Cut, Ground Fill, Hookup Wire, Solder Pad, Eyelet, Curved Trace]
> 00:53:34,666 DEBUG [main] Presenter - Tubes: [Tube Socket]
> 00:53:34,666 DEBUG [main] Presenter - Uncategorized: [ElectrolyticCanCapacitor]
> 00:53:34,666 DEBUG [main] Presenter - Shapes: [Line, Polygon, Ellipse, Rectangle]
> 00:53:34,666 DEBUG [main] Presenter - SMD: [SMD Resistor, SMD Capacitor]
> 00:53:34,746  INFO [main] MainFrame - injectGUIComponent(org.diylc.swing.plugins.toolbox.ComponentTabbedPane, 1)
> 00:53:34,776  INFO [main] Presenter - installPlugin(FileMenuPlugin)
> 00:53:34,778  INFO [main] MainFrame - injectMenuAction(New, File)
> 00:53:34,784  INFO [main] MainFrame - injectMenuAction(Open, File)
> 00:53:34,787  INFO [main] MainFrame - injectMenuAction(Import, File)
> 00:53:34,788  INFO [main] MainFrame - injectMenuAction(Save, File)
> 00:53:34,789  INFO [main] MainFrame - injectMenuAction(Save As, File)
> 00:53:34,790  INFO [main] MainFrame - injectDynamicSubmenu(Recent Files, icon, File)
> 00:53:34,791  INFO [main] MainFrame - injectMenuAction(Separator, File)
> 00:53:34,792  INFO [main] MainFrame - injectMenuAction(Export to PDF, File)
> 00:53:34,793  INFO [main] MainFrame - injectMenuAction(Export to PNG, File)
> 00:53:34,794  INFO [main] MainFrame - injectMenuAction(Print..., File)
> 00:53:34,795  INFO [main] MainFrame - injectSubmenu(Trace Mask, icon, File)
> 00:53:34,795  INFO [main] MainFrame - injectMenuAction(Export to PDF, Trace Mask)
> 00:53:34,796  INFO [main] MainFrame - injectMenuAction(Export to PNG, Trace Mask)
> 00:53:34,796  INFO [main] MainFrame - injectMenuAction(Print..., Trace Mask)
> 00:53:34,797  INFO [main] MainFrame - injectMenuAction(Create B.O.M., File)
> 00:53:34,797  INFO [main] MainFrame - injectMenuAction(Separator, File)
> 00:53:34,798  INFO [main] MainFrame - injectMenuAction(Exit, File)
> 00:53:34,803  INFO [main] Presenter - installPlugin(EditMenuPlugin)
> 00:53:34,803  INFO [main] MainFrame - injectMenuAction(Undo, Edit)
> 00:53:34,804  INFO [main] MainFrame - injectMenuAction(Redo, Edit)
> 00:53:34,804  INFO [main] MainFrame - injectMenuAction(Separator, Edit)
> 00:53:34,805  INFO [main] MainFrame - injectMenuAction(Cut, Edit)
> 00:53:34,806  INFO [main] MainFrame - injectMenuAction(Copy, Edit)
> 00:53:34,807  INFO [main] MainFrame - injectMenuAction(Paste, Edit)
> 00:53:34,808  INFO [main] MainFrame - injectMenuAction(Duplicate, Edit)
> 00:53:34,809  INFO [main] MainFrame - injectMenuAction(Separator, Edit)
> 00:53:34,810  INFO [main] MainFrame - injectMenuAction(Select All, Edit)
> 00:53:34,811  INFO [main] MainFrame - injectMenuAction(Edit Selection, Edit)
> 00:53:34,812  INFO [main] MainFrame - injectMenuAction(Delete Selection, Edit)
> 00:53:34,813  INFO [main] MainFrame - injectSubmenu(Transform Selection, icon, Edit)
> 00:53:34,814  INFO [main] MainFrame - injectMenuAction(Rotate Clockwise, Transform Selection)
> 00:53:34,815  INFO [main] MainFrame - injectMenuAction(Rotate Counterclockwise, Transform Selection)
> 00:53:34,815  INFO [main] MainFrame - injectMenuAction(Separator, Transform Selection)
> 00:53:34,816  INFO [main] MainFrame - injectMenuAction(Mirror Horizontally, Transform Selection)
> 00:53:34,817  INFO [main] MainFrame - injectMenuAction(Mirror Vertically, Transform Selection)
> 00:53:34,817  INFO [main] MainFrame - injectMenuAction(Separator, Transform Selection)
> 00:53:34,818  INFO [main] MainFrame - injectMenuAction(Nudge, Transform Selection)
> 00:53:34,819  INFO [main] MainFrame - injectMenuAction(Separator, Transform Selection)
> 00:53:34,820  INFO [main] MainFrame - injectMenuAction(Send Backward, Transform Selection)
> 00:53:34,821  INFO [main] MainFrame - injectMenuAction(Bring Forward, Transform Selection)
> 00:53:34,821  INFO [main] MainFrame - injectMenuAction(Separator, Transform Selection)
> 00:53:34,822  INFO [main] MainFrame - injectMenuAction(Group Selection, Transform Selection)
> 00:53:34,823  INFO [main] MainFrame - injectMenuAction(Ungroup Selection, Transform Selection)
> 00:53:34,823  INFO [main] MainFrame - injectMenuAction(Separator, Edit)
> 00:53:34,824  INFO [main] MainFrame - injectSubmenu(Renumber Selection, icon, Edit)
> 00:53:34,825  INFO [main] MainFrame - injectMenuAction(Top-to-Bottom, Renumber Selection)
> 00:53:34,825  INFO [main] MainFrame - injectMenuAction(Left-to-Right, Renumber Selection)
> 00:53:34,826  INFO [main] MainFrame - injectSubmenu(Expand Selection, icon, Edit)
> 00:53:34,827  INFO [main] MainFrame - injectMenuAction(All Connected, Expand Selection)
> 00:53:34,827  INFO [main] MainFrame - injectMenuAction(Immediate Only, Expand Selection)
> 00:53:34,828  INFO [main] MainFrame - injectMenuAction(Same Type Only, Expand Selection)
> 00:53:34,828  INFO [main] MainFrame - injectMenuAction(Separator, Edit)
> 00:53:34,829  INFO [main] MainFrame - injectMenuAction(Edit Project Settings, Edit)
> 00:53:34,833  INFO [main] Presenter - installPlugin(ConfigPlugin)
> 00:53:34,834  INFO [main] MainFrame - injectMenuAction(Anti-Aliasing, Config)
> 00:53:34,835  INFO [main] MainFrame - injectMenuAction(Auto-Create Pads, Config)
> 00:53:34,835  INFO [main] MainFrame - injectMenuAction(Auto-Edit Mode, Config)
> 00:53:34,835  INFO [main] MainFrame - injectMenuAction(Continuous Creation, Config)
> 00:53:34,836  INFO [main] MainFrame - injectMenuAction(Show Rulers, Config)
> 00:53:34,836  INFO [main] MainFrame - injectMenuAction(Show Grid, Config)
> 00:53:34,836  INFO [main] MainFrame - injectMenuAction(Export Grid, Config)
> 00:53:34,836  INFO [main] MainFrame - injectMenuAction(Hi-Quality Rendering, Config)
> 00:53:34,837  INFO [main] MainFrame - injectMenuAction(Mouse Wheel Zoom, Config)
> 00:53:34,837  INFO [main] MainFrame - injectMenuAction(Outline Mode, Config)
> 00:53:34,837  INFO [main] MainFrame - injectMenuAction(Snap to Grid, Config)
> 00:53:34,837  INFO [main] MainFrame - injectMenuAction(Sticky Points, Config)
> 00:53:34,838  INFO [main] MainFrame - injectSubmenu(Toolbox, icon, Config)
> 00:53:34,839  INFO [main] MainFrame - injectMenuAction(Searchable Tree, Toolbox)
> 00:53:34,840  INFO [main] MainFrame - injectMenuAction(Tabbed Toolbar, Toolbox)
> 00:53:34,841  INFO [main] MainFrame - injectSubmenu(Chassis, icon, Layers)
> 00:53:34,841  INFO [main] MainFrame - injectMenuAction(Visible, Chassis)
> 00:53:34,842  INFO [main] MainFrame - injectMenuAction(Lock, Chassis)
> 00:53:34,842  INFO [main] MainFrame - injectMenuAction(Select All, Chassis)
> 00:53:34,842  INFO [main] MainFrame - injectSubmenu(Board, icon, Layers)
> 00:53:34,842  INFO [main] MainFrame - injectMenuAction(Visible, Board)
> 00:53:34,843  INFO [main] MainFrame - injectMenuAction(Lock, Board)
> 00:53:34,843  INFO [main] MainFrame - injectMenuAction(Select All, Board)
> 00:53:34,843  INFO [main] MainFrame - injectSubmenu(Trace, icon, Layers)
> 00:53:34,844  INFO [main] MainFrame - injectMenuAction(Visible, Trace)
> 00:53:34,844  INFO [main] MainFrame - injectMenuAction(Lock, Trace)
> 00:53:34,844  INFO [main] MainFrame - injectMenuAction(Select All, Trace)
> 00:53:34,844  INFO [main] MainFrame - injectSubmenu(Component, icon, Layers)
> 00:53:34,845  INFO [main] MainFrame - injectMenuAction(Visible, Component)
> 00:53:34,845  INFO [main] MainFrame - injectMenuAction(Lock, Component)
> 00:53:34,845  INFO [main] MainFrame - injectMenuAction(Select All, Component)
> 00:53:34,845  INFO [main] MainFrame - injectSubmenu(Text, icon, Layers)
> 00:53:34,845  INFO [main] MainFrame - injectMenuAction(Visible, Text)
> 00:53:34,846  INFO [main] MainFrame - injectMenuAction(Lock, Text)
> 00:53:34,846  INFO [main] MainFrame - injectMenuAction(Select All, Text)
> 00:53:34,846  INFO [main] Presenter - installPlugin(LayersMenuPlugin)
> 00:53:34,849  INFO [main] MainFrame - injectMenuAction(Search The Cloud, Project Cloud)
> 00:53:34,850  INFO [main] MainFrame - injectMenuAction(Separator, Project Cloud)
> 00:53:34,851  INFO [main] MainFrame - injectMenuAction(Log In, Project Cloud)
> 00:53:34,852  INFO [main] MainFrame - injectMenuAction(Create New Account, Project Cloud)
> 00:53:34,852  INFO [main] MainFrame - injectMenuAction(Separator, Project Cloud)
> 00:53:34,853  INFO [main] MainFrame - injectMenuAction(Upload A Project, Project Cloud)
> 00:53:34,854  INFO [main] MainFrame - injectMenuAction(Manage My Uploads, Project Cloud)
> 00:53:34,855  INFO [main] MainFrame - injectMenuAction(Separator, Project Cloud)
> 00:53:34,856  INFO [main] MainFrame - injectMenuAction(Manage Account, Project Cloud)
> 00:53:34,857  INFO [main] MainFrame - injectMenuAction(Change Password, Project Cloud)
> 00:53:34,857  INFO [main] MainFrame - injectMenuAction(Log Out, Project Cloud)
> 00:53:34,858  INFO [main] Presenter - installPlugin(CloudPlugIn)
> 00:53:34,862  INFO [main] MainFrame - injectMenuAction(User Manual, Help)
> 00:53:34,863  INFO [main] MainFrame - injectMenuAction(FAQ, Help)
> 00:53:34,863  INFO [main] MainFrame - injectMenuAction(Component API, Help)
> 00:53:34,864  INFO [main] MainFrame - injectMenuAction(Plugin API, Help)
> 00:53:34,864  INFO [main] MainFrame - injectMenuAction(Submit a Bug, Help)
> 00:53:34,865  INFO [main] MainFrame - injectMenuAction(Separator, Help)
> 00:53:34,865  INFO [main] MainFrame - injectMenuAction(Donate, Help)
> 00:53:34,866  INFO [main] MainFrame - injectMenuAction(About, Help)
> 00:53:34,867  INFO [main] Presenter - installPlugin(HelpMenuPlugin)
> 00:53:34,870  INFO [main] ProxyFactory - Creating temp class code
> 00:53:35,076  INFO [main] ProxyFactory - Successfully instantiated proxy
> 00:53:35,076  INFO [main] MainFrame - injectGUIComponent(org.diylc.swing.plugins.statusbar.StatusBar, 3)
> 00:53:35,092  INFO [main] Presenter - installPlugin(StatusBar)
> 00:53:35,125  INFO [SwingWorker-pool-1-thread-3] UpdateChecker - Trying to download file: http://www.diy-fever.com/update.xml
> 00:53:35,126  INFO [main] Presenter - installPlugin(CanvasPlugin)
> 00:53:35,157  INFO [main] MainFrame - injectGUIComponent(org.diylc.swingframework.ruler.RulerScrollPane, 0)
> 00:53:35,200  INFO [main] Presenter - installPlugin(ComponentTree)
> 00:53:35,223  INFO [main] MainFrame - injectGUIComponent(org.diylc.swing.plugins.tree.TreePanel, 2)
> 00:53:35,226  INFO [main] Presenter - installPlugin(FramePlugin)
> 00:53:35,226  INFO [main] Presenter - installPlugin(AutoSavePlugin)
> 00:53:35,227  INFO [main] Presenter - createNewFile()
> 00:53:35,227  INFO [AWT-EventQueue-0] ConfigurationManager - Saving configuration
> 00:53:35,239  INFO [main] Presenter - loadProject(New Project, true)
> 00:53:35,241  INFO [main] UndoHandler - Resetting undo/redo
> 00:53:35,253  INFO [main] Presenter - loadProjectFromFile(D:\PEDALES\GUIT\1-DISTORSION-FUZZ-BOOSTER-PREAMP\EHX big muff\bigmuffALT.diy)
> 00:53:35,253  INFO [main] ProjectFileManager - loadProjectFromFile(D:\PEDALES\GUIT\1-DISTORSION-FUZZ-BOOSTER-PREAMP\EHX big muff\bigmuffALT.diy)
> 00:53:35,474 DEBUG [main] IconImageConverter - Reading image from file: 148x527
> 00:53:35,516  INFO [main] Presenter - loadProject(New Project, true)
> 00:53:35,517  INFO [main] UndoHandler - Resetting undo/redo
> 00:53:35,518  INFO [main] ConfigurationManager - Saving configuration
> 00:53:35,521  INFO [main] DIYLCStarter - Injecting default properties.
> 00:53:36,093 DEBUG [SwingWorker-pool-1-thread-2] PhpFlatProxy - Connecting to: http://www.diy-fever.com/diylc/api/v1/getAnnouncements.php
> 00:53:36,701 ERROR [AWT-EventQueue-0] MainFrame - Background task execution failed
> java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.diylc.announcements.Announcement
> 	at java.util.concurrent.FutureTask.report(Unknown Source)
> 	at java.util.concurrent.FutureTask.get(Unknown Source)
> 	at javax.swing.SwingWorker.get(Unknown Source)
> 	at org.diylc.swing.gui.MainFrame$4.done(Unknown Source)
> 	at javax.swing.SwingWorker$5.run(Unknown Source)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
> 	at sun.swing.AccumulativeRunnable.run(Unknown Source)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
> 	at javax.swing.Timer.fireActionPerformed(Unknown Source)
> 	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
> 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
> 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.awt.EventQueue.access$500(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.run(Unknown Source)
> Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.diylc.announcements.Announcement
> 	at org.diylc.announcements.AnnouncementProvider.getCurrentAnnouncements(Unknown Source)
> 	at org.diylc.swing.plugins.statusbar.StatusBar$1.doInBackground(Unknown Source)
> 	at org.diylc.swing.plugins.statusbar.StatusBar$1.doInBackground(Unknown Source)
> 	at org.diylc.swing.gui.MainFrame$4.doInBackground(Unknown Source)
> 	at javax.swing.SwingWorker$1.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at javax.swing.SwingWorker.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 00:53:36,704 ERROR [AWT-EventQueue-0] StatusBar - Error while fetching announcements
> java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.diylc.announcements.Announcement
> 	at java.util.concurrent.FutureTask.report(Unknown Source)
> 	at java.util.concurrent.FutureTask.get(Unknown Source)
> 	at javax.swing.SwingWorker.get(Unknown Source)
> 	at org.diylc.swing.gui.MainFrame$4.done(Unknown Source)
> 	at javax.swing.SwingWorker$5.run(Unknown Source)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
> 	at sun.swing.AccumulativeRunnable.run(Unknown Source)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
> 	at javax.swing.Timer.fireActionPerformed(Unknown Source)
> 	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
> 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
> 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.awt.EventQueue.access$500(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.run(Unknown Source)
> Caused by: java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.diylc.announcements.Announcement
> 	at org.diylc.announcements.AnnouncementProvider.getCurrentAnnouncements(Unknown Source)
> 	at org.diylc.swing.plugins.statusbar.StatusBar$1.doInBackground(Unknown Source)
> 	at org.diylc.swing.plugins.statusbar.StatusBar$1.doInBackground(Unknown Source)
> 	at org.diylc.swing.gui.MainFrame$4.doInBackground(Unknown Source)
> 	at javax.swing.SwingWorker$1.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at javax.swing.SwingWorker.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)
> 00:53:37,286  INFO [SwingWorker-pool-1-thread-3] UpdateChecker - 0 updates found
> 00:53:39,722  INFO [AWT-EventQueue-0] ActionFactory - ExportPDFAction triggered
> 00:53:44,071  INFO [AWT-EventQueue-0] ConfigurationManager - Saving configuration
> 00:53:44,077 DEBUG [SwingWorker-pool-1-thread-4] ActionFactory - Exporting to C:\Users\Francisco\Desktop\11.pdf
> 00:53:45,254 ERROR [AWT-EventQueue-0] MainFrame - Background task execution failed
> java.util.concurrent.ExecutionException: java.lang.NullPointerException
> 	at java.util.concurrent.FutureTask.report(Unknown Source)
> 	at java.util.concurrent.FutureTask.get(Unknown Source)
> 	at javax.swing.SwingWorker.get(Unknown Source)
> 	at org.diylc.swing.gui.MainFrame$4.done(Unknown Source)
> 	at javax.swing.SwingWorker$5.run(Unknown Source)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
> 	at sun.swing.AccumulativeRunnable.run(Unknown Source)
> 	at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
> 	at javax.swing.Timer.fireActionPerformed(Unknown Source)
> 	at javax.swing.Timer$DoPostEvent.run(Unknown Source)
> 	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
> 	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
> 	at java.awt.EventQueue.access$500(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.awt.EventQueue$3.run(Unknown Source)
> 	at java.security.AccessController.doPrivileged(Native Method)
> 	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
> 	at java.awt.EventQueue.dispatchEvent(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
> 	at java.awt.EventDispatchThread.run(Unknown Source)
> Caused by: java.lang.NullPointerException
> 01:05:12,019  INFO [AWT-EventQueue-0] ConfigurationManager - Saving configuration

**Comment by animalejo** [comment]
now i see that's happen only with one project, i didn't make any particular work or something strange, just new project like any others. i don't know what happen...

**Comment by bancika** [comment]
I see. When you open any other projects it works fine? If so, could you please upload the project itself, you can upload directly here. I'll debug on my side.

**Comment by animalejo** [comment]
here you go:

https://www.dropbox.com/s/689f0a80ghkwkjs/bigmuffALT.diy?dl=0

Thanks

**Comment by animalejo** [comment]
i forget....no problem with other projects

**Comment by bancika** [comment]
interesting, it works fine in my DIYLC v40. Generated PDF with no issue. Which leads me to believe that there's something about the local configuration. Maybe it saved some bad setting or something. That's the only explanation I have. I assume that restart of the app doesn't help either. Could you upload config.xml from .diylc? Cheers

**Comment by animalejo** [comment]
yeah, restart doesn't work, definility is only with that project :(

there you go: https://www.dropbox.com/s/zkjwfqm7zo73ft9/config.xml?dl=0

**Comment by animalejo** [comment]
dude i solved the problem, it was the Font !!
i use this one: https://www.dropbox.com/s/ow5axgjyev3nndm/diylcissuefont.jpg?dl=0
if i delete it the problem is gone...
maybe the font is corrupted or something, i don't know

Thanks anyway
great app ! i'm wait for the new version jejeje
Cheers !!

**Comment by bancika** [comment]
ha! Cool. I don't have that font so it worked here even with your config because it replaced that font with default. I'll check that font out and see what it does to the process.

Cheers

**Comment by bancika** [comment]
btw, great looking layout!

**Comment by animalejo** [comment]
thanks dude

cheers from Chile
