### ISSUE TITLE
Suggestion - Oval pads for ICs

### ISSUE THREAD

**Issue by kroma-1** [bancika/diy-layout-creator#346]
Perhaps it would be useful to have oval pads for ICs, so traces con be run between them, and still have enough "pad space" to tin the IC pins correctly and safely. 
Thanks for listening.

**Comment by bancika** [comment]
already have oval pads, I think oval are default, no?

**Comment by N9XYP** [comment]
Round (default) or square in 3.40

**Comment by kroma-1** [comment]
Yes, round or square only.

**Comment by bancika** [comment]
Ah gotcha.

**Comment by bancika** [comment]
added for 3.46
