### ISSUE TITLE
Linux, Application gets stuck on loading (empty window)

### ISSUE THREAD

**Issue by fiechr** [bancika/diy-layout-creator#347]
I'm using DIYLC on different Linux systems. On Manjaro (Arch based) I'm having the issue, that I can't launch the application after exiting it and starting it a second time. After a reboot it starts up fine again (without doing anything else!).

I found out, that it works again, without reboot, if I _remove_ this part from the config.xml:
```xml
<entry>
  <string>abnormalExit</string>
  <boolean>true</boolean>
</entry>
```

Simply setting it to "false" doesn't work.

Don't know why this entry is created, since the app was closed regularly before, no errors or anything like that (at least not in the GUI). In fact this entry seems to be created when the application is still running.

I'm using the Oracle JRE 9.x (latest).

These are the last lines in the log if the software **fails** to start:
```
[...]
18:42:08,844  INFO [main] DIYLCStarter - Injecting default properties.
18:42:09,258  INFO [SwingWorker-pool-1-thread-3] UpdateChecker - 0 updates found
18:42:09,611 DEBUG [SwingWorker-pool-1-thread-2] PhpFlatProxy - Connecting to: http://www.diy-fever.com/diylc/api/v1/getAnnouncements.php
```

And this is the same part when it works:
```
[...]
18:49:54,356  INFO [main] DIYLCStarter - Injecting default properties.
18:49:54,703  INFO [SwingWorker-pool-1-thread-3] UpdateChecker - 0 updates found
18:49:55,192 DEBUG [SwingWorker-pool-1-thread-2] PhpFlatProxy - Connecting to: http://www.diy-fever.com/diylc/api/v1/getAnnouncements.php
18:49:55,349 ERROR [AWT-EventQueue-0] MainFrame - Background task execution failed
java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.base/java.util.ArrayList cannot be cast to org.diylc.announcements.Announcement
[...]
18:49:55,355 ERROR [AWT-EventQueue-0] StatusBar - Error while fetching announcements
[...]
```

**Comment by bancika** [comment]
it should work now, that flag is decommissioned.
