### ISSUE TITLE
BOM export to excel does not work

### ISSUE THREAD

**Issue by jojokeo** [bancika/diy-layout-creator#348]
I've tried naming the old way *.xls and the newest version *.xlsx - neither work!

**Comment by bancika** [comment]
which OS are you using?

**Comment by jojokeo** [comment]
Windows 7 professional

Sent from my iPhone

On Mar 13, 2018, at 9:08 AM, bancika <notifications@github.com<mailto:notifications@github.com>> wrote:


which OS are you using?

**Comment by EL34xyz** [comment]
I can verify that BOM save to Excel .xls is not working for me either.
The save dialog box opens and I type a file name, but the file is never saved where I have specified
Save to csv, png and html all work fine for me

Windows 7 pro here also
I have Microsoft Office installed  on this desktop

**Comment by bancika** [comment]
fixed in 3.42.0

**Comment by jojokeo** [comment]
Hello Bancika!


I only see version 3.41.1 available. Can you say when version 3.42.0 will become available?


Thank you!

Jojokeo


________________________________

**Comment by EL34xyz** [comment]
Bancika posted on the facebook DIYLC group that he is working on adding a few more fixes and new features before doing the next release
You should join the group here
https://www.facebook.com/groups/866347656903552/
