### ISSUE TITLE
Vacuum tubes cannot rotate

### ISSUE THREAD

**Issue by olduvai** [bancika/diy-layout-creator#349]
Ver. 3.40, 3.39, 3.36 tested and tubes cannot be rotated. An error popup states not all components of the selection can be rotated.

Ver. 3.31 can properly rotate tubes CW and CCW.

**Comment by bancika** [comment]
you should be able to type in exact angle to rotate

**Comment by olduvai** [comment]
Yes that works. Didn't know about that option in the newer version.
