### ISSUE TITLE
Idea: Set default filename for exporting PDF and/or PNG files

### ISSUE THREAD

**Issue by fiechr** [bancika/diy-layout-creator#351]
Here is an idea. If the user wants to export a PDF or PNG from the current drawing/circuit she/he has to provide a new filename first. I think it would be a good idea to set the filename of the currently open file (if already saved) as default value.

So for example: If I want to export "MyGreatCircuitV1.diy" as PDF, the save dialog will automatically suggest "MyGreatCircuitV1.pdf" as filename.

**Comment by bancika** [comment]
good one

**Comment by EL34xyz** [comment]
Good suggestion
Same with all saved files - Tack on the file name in front
Exports and BOM come up with blank file names

**Comment by bancika** [comment]
done in 3.44
