### ISSUE TITLE
Trim pot outline is too big, DIYLC v3.37

### ISSUE THREAD

**Issue by jschreiberaudio** [bancika/diy-layout-creator#355]
The trim pot outline shows it takes up a 5x5 area on 0.1 in. pitch breadboard. The trim pots I use are only 3x3 for the same pitch.  I know I could just overlay on top of the outline, but it makes a mess trying to decipher the part map.  This is a little thing but also big help if a smaller 3x3 trim pot outline could be added.  Thanks -Jason

**Comment by bancika** [comment]
added for 3.42
