### ISSUE TITLE
(MacOS) .app won't open

### ISSUE THREAD

**Issue by martinloren** [bancika/diy-layout-creator#357]
The JavaApplicationStub file seems corrupted. System message on opening:

“JavaApplicationStub” is damaged and can’t be opened. You should move it to the Trash.

File diylc.jar can open and the App works correctly. Please fix the Stub file, thanks!

**Comment by jonathanfann** [comment]
https://github.com/bancika/diy-layout-creator/issues/364#issuecomment-427589732 i made this automator workflow if you're interested in how

**Comment by bancika** [comment]
dupe of #364
