### ISSUE TITLE
Building Blocks not available in Toolbox Tabbed Toolbar

### ISSUE THREAD

**Issue by aelling84** [bancika/diy-layout-creator#362]
The building block seems to only be available when the Toolbox is set to Searchable Tree. It would be great if it would be available in the Tabbed Toolbar.

Thanks for a great freeware.

**Comment by EL34xyz** [comment]
Confirmed. Same here in windows 7 pro and latest DIYLC version

**Comment by bancika** [comment]
That was never implemented. I thought everyone used the tree :)

**Comment by bancika** [comment]
done for 4.15
