### ISSUE TITLE
Mac OSX 10.12.6 'Sierra' cannot open App

### ISSUE THREAD

**Issue by SonusMagus** [bancika/diy-layout-creator#364]
I am getting the malicious app warning and being told to move the App to the Trash. 

I have followed instructions to mark the App as excluded and not getting any joy

It will not start from run.sh either

Any advice appreciated

Thanks

**Comment by jonathanfann** [comment]
I encountered this same issue.  I ended up creating an Automator Application that ran a shell script: 

`open /{{ path to the app }}/DIYLC\ 2.app/Contents/Resources/Java/diylc.jar`

the first time you need to actually right click the file there ^ and hit open (this allows you to run it in the automator script...).  sorry that's kinda complicated.  

anyways, it does a little pop up like "you shouldn't open this this way" (from the app, not from MacOS), but click yes and you'll be making stripboard layouts on mac again.  but yeah, this is a pretty bad workaround, but if you're willing to put in the time to set it up, it's not so bad once you get it rolling.

I even added a stupid icon to mine and plopped it in whatever that bar at the bottom is called: 
![image](https://user-images.githubusercontent.com/7726998/46573760-c3e24300-c967-11e8-8ba1-de73d6b0564d.png)

**Comment by SonusMagus** [comment]
thanks Jonathan that works cleaner than what I have been doing ;/)
so I wonder if there's an advantage over simply dragging the .jar out of the broken App and double clicking it?
thanks

**Comment by bancika** [comment]
There is an advantage. Double clicking the .jar starts the application without the recommended memory settings and potentially other stuff. It'll work either way, though.

**Comment by martinloren** [comment]
I made a package to fix the opening issue n Mac OSX. For future release just update the .jar file inside and eventually other contents. The framework will continue to work.
Issue:
- it still show the message to do not open it directly by the .jar file. Just need to click OK each time you open the app.
- Once opened it show version 0.0 (a bug in the .jar?) so it always says that there is a new release to download.

[diylc.app.zip](https://github.com/bancika/diy-layout-creator/files/2816330/diylc.app.zip)

**Comment by bancika** [comment]
Thanks!

Hmm, the version is read from update.xml file, which probably means that it doesn't have correct access to that file. Also, do you see factory variants? For example, IC component should have 2 of them. Those are stored in variants.xml file. It's possible that that's another issue.

What did you use to generate the app? I have automated process for building deploy packages for all platforms, wondering how I could automate this. What's different compared to my app package?

Thanks!

**Comment by martinloren** [comment]
This is the tool that works: jar2app 1.0.1 (https://github.com/Jorl17/jar2app)
I've just generated an app with just the .jar inside, then in Mac OS is possible to open the .app packages and drop inside the files/modify, so I put all other files and it worked. I'm trying to load the XML changing folders inside the package. I see on the app title bar it show version 0.0 but in About box it show version 3.0.0.

The .xml file is also the latest one but inside it report:

			<versionNumber>
				<major>3</major>
				<minor>0</minor>
				<build>4</build>
			</versionNumber>

**Comment by martinloren** [comment]
This version should show also App Icon (I just put in the right folder linking with the .pinfo file).
Variants XML works fine, I tried to move out and it don't work, move in and it show all variants. Version XML is in the same folder of Variants XML but still have that issue.

[DIYLC.app.zip](https://github.com/bancika/diy-layout-creator/files/2816522/DIYLC.app.zip)

**Comment by bancika** [comment]
Sorry for asking, I'm not a mac user so not sure how everything works. Which issue is this build solving? I tried the "official" OSX build on a sierra and once you allow it in the gatekeeper, it runs fine. Is there any other issue I'm not aware of?
Tnx again

**Comment by martinloren** [comment]
I've tried several releases for Mac OSX and none could start even if authorized. I've always used the trick to open the .jar before.

Here the screenshot of the message that appean when you try to open the app on Mac. (Click on the App and then -> Open)
![snip20190201_1](https://user-images.githubusercontent.com/37680207/52092869-0c4afe00-25f4-11e9-9a7e-57a5c3bf7154.png)

**Comment by bancika** [comment]
I use eclipse. Tried replacing the jars in the zip with the latest build but getting this error on my sierra VM

![image](https://user-images.githubusercontent.com/11462281/52572496-38e2ef00-2e18-11e9-8730-4b35eb4e6c75.png)

**Comment by spyrosze** [comment]
I faced the same app warning on Mac OS 10.14.5 Mojave and had to run the terminal trick to open the app. Type this in terminal. 
`xattr -cr /path/to/app`

@bancika this tool seems really *fantastic*  congrats! I am familiar with the drawings as a DIY effects builder and looking forward to use it to draw schematics. I am a UX designer by trade and I'll be more than happy to provide feedback when I get to use it. One thing that seems strange is the pixelated font on my [Mac](https://www.dropbox.com/s/1ady85cgxjtj1x1/Screenshot%202019-05-23%2016.21.37.png?dl=0).
