### ISSUE TITLE
Copying a group does not preserve z-indexes of grouped elements

### ISSUE THREAD

**Issue by sehrgut** [bancika/diy-layout-creator#366]
While attempting to mock up a trimpot, I discovered that copied groups do not preserve z-indexes of grouped elements.

To reproduce:
1. Create multiple overlapping shapes.
2. Group the shapes.
3. Copy the group.
4. Paste the group.

What I expect: A group to be pasted with elements arranged identically to the parent group.

What happens: A group is pasted that has the elements arranged in a different z-order from the parent group.

**Comment by bancika** [comment]
included in 3.42.0
