### ISSUE TITLE
Tick on Electrolytic get covered by text

### ISSUE THREAD

**Issue by aelling84** [bancika/diy-layout-creator#368]
Because the value/name text on Electrolytic capacitors are vertical, the little '-' tick gets covered by either the 'F' or the number. Since these caps will mostly have the negative indicator up/down on vero board, maybe make it so you can select whether the text is vertical or horizontal so it works for people making perf boards with the caps side ways.

**Comment by bancika** [comment]
Added "Label Orientation" property to leaded components that can be used to force labels to be rendered horizontally instead of following component placement direction
