### ISSUE TITLE
Feature request - Dashed/Dotted Hookup Wire 

### ISSUE THREAD

**Issue by EL34xyz** [bancika/diy-layout-creator#380]
This is just future feature request
Many people in the Tube amp community use dashed or dotted wires to indicate that a wire runs under a board as a jumper wire.
I do this in MS Visio for all my Hoffman turret board layouts

It would be nice to be able to do this in DIYLC also

I attached a screen shot showing what these under board jumper wires look like in Visio
Thanks Bancika

![image1](https://user-images.githubusercontent.com/16766383/50054439-c7d0d500-010f-11e9-9705-fd4f336a53f9.png)

**Comment by bancika** [comment]
[diylc-3.43.0.zip](https://github.com/bancika/diy-layout-creator/files/2688071/diylc-3.43.0.zip)

**Comment by kroma-1** [comment]
Dotted or dashed lines aren`t working for me. The options are there, but nothing changes.

**Comment by EL34xyz** [comment]
Dotted and dashed lines work fine for me in  windows 7 pro

![lines](https://user-images.githubusercontent.com/16766383/50120627-2d15ea80-0224-11e9-9c72-c87c9c6ce2d7.png)

**Comment by EL34xyz** [comment]
bancika is still testing several line features with me. 
Hang loose while we work some stuff out

**Comment by bancika** [comment]
releasing as part of 3.43
