### ISSUE TITLE
[Mac OS] Command + Scroll up/down on trackpad for zoom broken

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#387]
Log attached. 

Issue new to v3.46, does not reproduce in v3.45
DUT: Macbook Air with Mac OS 10.14.1

Reproduction:
1. Open a .DIY file
2. Attempt to zoom in or out on the file by holding down command key while scrolling up or down on mouse trackpad.

Expected result: 
The image zooms in or out as user intends

Actual result:
No zooming.

**Comment by bancika** [comment]
Please try 3.46.1

**Comment by JackMillerSD** [comment]
> Please try 3.46.1

Confirmed that this now works again.

**Comment by iiimonfiiire** [comment]
Verified fixed. Thank you for fixing this so quickly!!
