### ISSUE TITLE
I'm seeing,"“DIYLC.app” is damaged and can’t be opened. You should move it to the Trash." 

### ISSUE THREAD

**Issue by MrYanasak** [bancika/diy-layout-creator#390]
Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates

**Comment by MrYanasak** [comment]
I'm having issues starting the application under MacOS, (MacOs 10.14.2 and Java 8). I followed the link to make sure that 3rd party apps are allowed on my Mac (I think so anyway). I found similar "resolved" issues that were already reported (#264), but yet here I am with no way to open and use this tool.

**Comment by mPacT001** [comment]
I have High Sierra 10.13.6 and kept getting the damaged file message. This is what worked.

Go into terminal and paste this:

sudo spctl --master-disable

You will need to put in your system password. Then, open DIYLC, make sure it works then go back to terminal and paste this.

sudo spctl --master-enable

Should work fine.

**Comment by MrYanasak** [comment]
Yes! Thank You! Beautiful! That worked.

**Comment by DaniTeOdia** [comment]
> I have High Sierra 10.13.6 and kept getting the damaged file message. This is what worked.
> 
> Go into terminal and paste this:
> 
> sudo spctl --master-disable
> 
> You will need to put in your system password. Then, open DIYLC, make sure it works then go back to terminal and paste this.
> 
> sudo spctl --master-enable
> 
> Should work fine.

Same issue and same solution to me!

Just Enable/Disable Master on Terminal to evitate crash installation on OSX. 
Worked fine to me on **OS High Sierra 10.13.6**  i7 2.7Gh MacBookPro Early 2011 

Thanks to Bancika an the community for the great job.
Stay DIYER! 
Get strength and sharing knowledge!
