### ISSUE TITLE
sith WIndows 10, MyEclipse 2017, java 1.8 & ant 1.7, I get this error when I run execute an ant build on build.xml: BUILD FAILED D:\code\diylc\src\diylc\diylc-swing\build.xml:119: Execute failed: java.io.IOException: Cannot run program "innosetup\iscc.exe" (in directory "D:\code\diylc\src\diylc\diylc-swing"): CreateProcess error=2, The system cannot find the file specified.  Any thoughts?  Maybe my environment in MyEclipse is lacking something? I checked and "innosetup\iscc.exe" does exist in the diylc-swing folder as it should.

### ISSUE THREAD

**Issue by shouse1953** [bancika/diy-layout-creator#402]
Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates.
* Make sure that you are running the latest version of DIYLC.

**Comment by shouse1953** [comment]
MyEclipse issue.

**Comment by bancika** [comment]
Cool, btw, can you please follow the convention of shorter issue title and put all the info in the description. It's easier to follow.

**Comment by shouse1953** [comment]
Yep
