### ISSUE TITLE
Two ideas

### ISSUE THREAD

**Issue by MartinKobza** [bancika/diy-layout-creator#405]
Thank you for a nice project, two ideas:
- flipping a board to see the copper side would simplify orientation when soldering copper traces
- some perfboards (tripad boards) use opposite numbering of coordinates (rows are numbers, columns are characters), it could be an option

**Comment by bancika** [comment]
I'll add the second request to the queue. The first one you can already do. Just select all from Trace layer (Layers -> Trace -> Select All), copy to the blank area of the canvas and do "Flip Horizontally"

**Comment by bancika** [comment]
done for 3.50
