### ISSUE TITLE
Dual monitor Display issue in 49.0

### ISSUE THREAD

**Issue by EL34xyz** [bancika/diy-layout-creator#406]
I just DL'd and installed 49.0. Found a weird bug. 
I run two 23 inch LED monitors in windows 7 pro.
Running the program on the main monitor is fine.
Dragging the program to the extended monitor results in the work area going black. 
The tools on the left side are fine, just the work area goes black

Here's a screen shot of that and my windows monitor setup

![monitor](https://user-images.githubusercontent.com/16766383/51264860-6eb1c680-1985-11e9-95a5-c29b6e3179c4.png)

![extended](https://user-images.githubusercontent.com/16766383/51264869-74a7a780-1985-11e9-8a50-318f6c14ad05.png)

**Comment by EL34xyz** [comment]
Bancika told me to comment out a couple lines in this file
It works fine now
C:\Program Files (x86)\DIYLC\config.properties

![49937670_10156988870583659_4790474687937249280_n](https://user-images.githubusercontent.com/16766383/51265365-a1a88a00-1986-11e9-90b6-f55990f32f08.jpg)

**Comment by bancika** [comment]
fixed for 3.50
