### ISSUE TITLE
curve traces render 10% thicker.

### ISSUE THREAD

**Issue by kroma-1** [bancika/diy-layout-creator#407]
I opened a project created in V 46.1, and curve traces appear 10% (aprox.) thicker, although they are 1mm. 
I´m attaching 2 screenshots. Pay attention to the second one, the bottom black line is a straight line, 2mm., and the red on top is a "rectified" curve, same width.

I know this is a small issue, but its visually annoying (OCD speaking)

![traces](https://user-images.githubusercontent.com/30356163/51404373-07854500-1b32-11e9-93d2-18c752567c21.png)
![traces_2](https://user-images.githubusercontent.com/30356163/51404374-07854500-1b32-11e9-961b-5b5bac635cb6.png)

**Comment by bancika** [comment]
not sure what the issue is since your screenshot shows two different layouts :) in which version do you find the traces to be ticker? Are those curved traces? Your second screenshot has a straight trace selected. Not sure where I'm supposed to look at :)

**Comment by bancika** [comment]
maybe I understood what you were saying (although I'm still not sure where to look at)...curved traces are rendered 1px wider than straight traces of the same thickness. If that's the case, I'll fix for 3.50

**Comment by kroma-1** [comment]
Those are 2 sections of the same layout. The red one in the second capture is not a selected trace, its a curve but straightened and superimposed on the black one.
Also, I marked where a curves join straight traces.
![traces_2](https://user-images.githubusercontent.com/30356163/51414082-efbcb980-1b4f-11e9-9835-1cc1af045c8f.png)

**Comment by kroma-1** [comment]
I´d say about 2px wider... ;)
Thanks.

**Comment by bancika** [comment]
gotcha, yeah, I think I fixed it. Thanks.
