### ISSUE TITLE
Request Measure tool (PCB Measure)

### ISSUE THREAD

**Issue by MacFly77** [bancika/diy-layout-creator#409]
Would it be possible to add a measure tool so I can measure what was drawn.
I would like to know the size of the PCB I draw. 
If a measure tool is not possible maybe the measurements of the rectangle can be returned in some way. I usually put a white rectangle below my traces for the PCB size.

**Comment by bancika** [comment]
did you try selection measurement tool from the status bar?

![image](https://user-images.githubusercontent.com/11462281/51425817-85ecf000-1be1-11e9-8eb2-8e301366ddfb.png)

**Comment by MacFly77** [comment]
Never knew it was there...closed!
