### ISSUE TITLE
Hardware acceleration 3.49.0 in WIndows 7 and Java 1.8.201 not working properly

### ISSUE THREAD

**Issue by PH0MB** [bancika/diy-layout-creator#410]
When starting V3.49 in windows and java 1.8.201 or OpenJava 11 the dawing canvas is not showing anything but a black screen. Altering the  config.properties and commenting out the accelleration restores 
functionality. 

# Uncomment lines you want to edit and change the part after the "=" sign.
#org.diylc.presenter.InstantiationManager.MAX_RECENT_COMPONENTS=20
#org.diylc.swing.plugins.canvas.CanvasPanel.USE_HARDWARE_ACCELLERATION=true
#org.diylc.swingframework.ruler.Ruler.USE_HARDWARE_ACCELLERATION=true
#org.diylc.swing.gui.editor.PropertyEditorDialog.SHOW_DEFAULT_BOXES=true

Using NVIDIA NVS310 card 347.52 driver.
V3.48 works OK.

**Comment by bancika** [comment]
Yes, I noticed that it doesn't work on some machines, so now it's moved into Config menu and will be disabled by default starting 3.50.
Thanks
