### ISSUE TITLE
A couple of bugs in the latest versions

### ISSUE THREAD

**Issue by stinga11** [bancika/diy-layout-creator#411]
Hi, I am using Windows 10 with Java 8. I created a couple of layouts with v48.0 but I can not open them with v49.0 and v50.0. When I open the project, an error appears. Another thing when I tried to use the ohms resistors with v50.0 appear a few rare symbols instead of the symbol of ohms.

**Comment by bancika** [comment]
can you please upload one of the files that doesn't work?

**Comment by stinga11** [comment]
[invento nuevo.zip](https://github.com/bancika/diy-layout-creator/files/2789621/invento.nuevo.zip)

**Comment by bancika** [comment]
Oh, I got it. In 3.48 I added a property for IEC socket that was removed in 3.50. I thought that nobody started using the component so I removed the unused param...if you delete this line from your DIY file, it will start working.

<hasFuse>false</hasFuse>

**Comment by bancika** [comment]
Btw, I'll fix the ohm render
