### ISSUE TITLE
Selecting a jumper sets its colour to red 

### ISSUE THREAD

**Issue by timsavage** [bancika/diy-layout-creator#412]
Version: 3.50
OS: GNU/Linux - Ubuntu 18.04 64bit
JRE: Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
Log: [log-2019-01-24 06.17.58.txt](https://github.com/bancika/diy-layout-creator/files/2791075/log-2019-01-24.06.17.58.txt)

When selecting a jumper it goes red as expected, however, after selecting another component the previous colour is not restored. Even after selecting an alternate colour (via edit dialogue). This doesn't seem to affect hookup wires or other components.

Steps to reproduce
- Draw a jumper wire
- Select the jumper

**Comment by bancika** [comment]
hmm, I just tried and it worked fine, although under windows 10.
Does it work ok with earlier versions, like 3.45?

**Comment by timsavage** [comment]
After doing a bit more testing I've found that this also affects resisters when they are standing up.

Tested with 3.48, this version does not exhibit the same issue.

**Comment by EL34xyz** [comment]
Ok, I see now that selecting the jumper changes it to red permanently as was reported
I was thinking that sending it backward was the culprit
This is in 50.0 on Windows 7 pro

**Comment by EL34xyz** [comment]
I am not seeing a problem with resistors in 50.0  as was reported. 
Can you tell me the exact component you used?

**Comment by EL34xyz** [comment]
Ok, I see what timsavage was saying about resistors
I think this is an issue of changing the angle of a component
I just saw the leads of the resistor on the left change to red after changing the angle or orientation

![resistor](https://user-images.githubusercontent.com/16766383/51758939-005fb900-2095-11e9-90f4-dbba9bcfb6d1.png)

**Comment by EL34xyz** [comment]
If you open the edit selection menu, you can change the Red leads back to the original color. 
FF0000 is the color that the leads were changed to
CCCCCC is the original lead colors that I use

![leads](https://user-images.githubusercontent.com/16766383/51760336-394d5d00-2098-11e9-82da-4e00ef89412b.png)

**Comment by bancika** [comment]
fixed for 3.51
