### ISSUE TITLE
Ohm not selectable in resistor drop down menu

### ISSUE THREAD

**Issue by EL34xyz** [bancika/diy-layout-creator#414]
Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates.
* Make sure that you are running the latest version of DIYLC.

**Comment by EL34xyz** [comment]
50.0 - windows 7 pro

There is some sort of funky characters in the value drop down box for resistors
Ohm symbol is not there

![ohm](https://user-images.githubusercontent.com/16766383/51754729-10729b00-208b-11e9-97ed-97f9022e03cb.png)

**Comment by bancika** [comment]
fixed for 3.51

**Comment by EL34xyz** [comment]
Thanks
