### ISSUE TITLE
horizontal and vertical line rendering

### ISSUE THREAD

**Issue by robert-rozee** [bancika/diy-layout-creator#417]
an issue seems to have been introduced recently (present in releases 49 and 50) whereby some horizontal and vertical lines running into components have been knocked off-grid. see attached gif. also, as reported elsewhere, the ohm symbol is not working correctly - was ok with release 49, now broken in release 50.

cheers,
rob   :-)

**Comment by robert-rozee** [comment]
seems there is also an issue with github refusing to allow images to be attached any more. email me and i'll send you a copy of the magnified image of a resistor. 800% view of an exported pdf.

**Comment by bancika** [comment]
Fixed for 3.51
