### ISSUE TITLE
Margins in print dialog get reset

### ISSUE THREAD

**Issue by pedalmeat** [bancika/diy-layout-creator#419]
Hi 

When trying to set margins in print dialog they all get reset to 1.0 inch when the "left" textbox loses focus using keyboard tab-key or mouse. Don't know if this is a bug or a feature.

I am using Linux 3.16.0-7-amd64 #1 SMP Debian 3.16.59-1 (2018-10-03) x86_64 GNU/Linux and and running diylc with Java 1.7.0_181 OpenJDK Runtime Environment (IcedTea 2.6.14) (7u181-2.6.14-2~deb8u1) OpenJDK 64-Bit Server VM (build 24.181-b01, mixed mode)
 
[log-2019-01-30 08.12.12.txt](https://github.com/bancika/diy-layout-creator/files/2814201/log-2019-01-30.08.12.12.txt)

**Comment by pedalmeat** [comment]
Hi bancika

I apologize for the late answer. A screenshot is attached. This is from the latest release 3.56.0

![gkrellShoot_2019-03-22_162602](https://user-images.githubusercontent.com/47191894/54834574-bb38bb80-4cc0-11e9-8e00-4cf1e1d94cb6.jpg)


Nikola

**Comment by bancika** [comment]
Thanks. That must be something related to that distribution of linux, it's definitely not a dialog I've built or have control over.
