### ISSUE TITLE
1/4 jack Close circuit

### ISSUE THREAD

**Issue by stinga11** [bancika/diy-layout-creator#427]
Hi, I wanted to know if it is possible that you add the 1/4 Jack closed circuit. It is used a lot in amplifiers layout. In your wonderful program is not available. Thanks

**Comment by bancika** [comment]
not sure I follow, do you have a photo?

**Comment by stinga11** [comment]
In the program you have the 1/4 Jack open circuit that has two pin. But in the amps we use the 1/4 Jack closed 
![images](https://user-images.githubusercontent.com/8172880/52493937-109e8a80-2ba3-11e9-8807-4df520d3d203.jpeg)
circuit that has three pin for the speaker output and the guitar input. Here I leave the photo

**Comment by stinga11** [comment]
switchcraft 12a

**Comment by bancika** [comment]
but you already have that as "Open Jack"
![image](https://user-images.githubusercontent.com/11462281/52501088-cc7dab00-2bdf-11e9-914e-eda3aa733ef4.png)

**Comment by stinga11** [comment]
its not the same thing

Stereo(Tip,Ring,Sleeve)
![w-sc-12b_switching_diagram](https://user-images.githubusercontent.com/8172880/52502598-9299ae00-2bb9-11e9-8d9e-e58650eb6b9b.png)
Mono Closed circuit(Tip,Tip Shunt,Sleeve)
![w-sc-12a_switching_diagram](https://user-images.githubusercontent.com/8172880/52502600-9299ae00-2bb9-11e9-82e8-0fac87b0c81f.png)

**Comment by bancika** [comment]
I see what you mean now
