### ISSUE TITLE
AWG to mm2

### ISSUE THREAD

**Issue by daturach** [bancika/diy-layout-creator#435]
Hello
Thanks for making this software available. 
I just started using it. 
One quick question: is it possible to "switch" from AWG to mm2?
Regards
Walter

**Comment by bancika** [comment]
Not in the current version. I'll consider adding something for the future. At a minimum, we can have mm2 value in parenthesis next to AWG number.

**Comment by daturach** [comment]
I think it should be fine to have it in ( ). Sorry, I am not used to AWG. There is something not logical to me: small number, big section :-)

**Comment by bancika** [comment]
alright, yeah it's not logical at all. I'll add it
