### ISSUE TITLE
version 54 image issues

### ISSUE THREAD

**Issue by EL34xyz** [bancika/diy-layout-creator#438]
Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates.
* Make sure that you are running the latest version of DIYLC.

**Comment by EL34xyz** [comment]
I am testing version 54 by adding images
Note that this same thing happened on older versions

I added a .png image that is 9.389 inches wide x 3.861 inches tall
It is a 72 pixels per inch PNG image

After adding it to DIYLC
It displays in DIYLC as 3.38 inches wide x 1.39 inches tall

How come DIYLC shrinks the image down so much?
You can't even move the size slider far enough to get the image up to the original size

Here's a couple screen shots
One is from my image editor program - Paint Shop Pro
The other one is how it displays in DIYLC

![imagesize2](https://user-images.githubusercontent.com/16766383/53422399-6483de80-39ad-11e9-8b74-53da8f91d101.png)

![imagesize](https://user-images.githubusercontent.com/16766383/53422404-664da200-39ad-11e9-9163-5fa8e2c86684.png)

**Comment by EL34xyz** [comment]
Here's another issue I ran into when adding images

After clicking on the image icon to load an image, I get an error dialog box
The image does load and then the dialog box goes away

Then I added some text below the image and edited the text
That produced the error dialog box also but the edited text did display and the box closed

Here's a couple screen shots
One is while loading the image
The other one is after I edited the text below the image

![textediterror](https://user-images.githubusercontent.com/16766383/53422920-5f735f00-39ae-11e9-8ca1-de508ca884b1.png)

![imageerror](https://user-images.githubusercontent.com/16766383/53422893-54203380-39ae-11e9-8f02-bc63999d2cad.gif)

**Comment by bancika** [comment]
can you upload the logs please?

**Comment by EL34xyz** [comment]
Ok, the error message boxes are gone now when I add an image and add/edit text under the image

The image size is still goofy
You have to multiply the imported image size x 2.77 to get the real image size of 9.39 inches
The image slider only goes to 254% which is not enough to get the image to the proper scale

**Comment by bancika** [comment]
It's the difference in DPI. Your file is 72dpi while DIYLC draws in 200dpi. That's where the 2.77 comes from.

Not sure how to deal with it because file DPI can be anything, not just 72dpi. I could pre-scale by 2.77 but some other files might get wacky.

**Comment by EL34xyz** [comment]
Ok, did not know it was 200 dpi

Most images people are going to use are the standard 72 dpi
If you take a screen shot from a PDF, those are usunally 96 dpi

Also, a 200 dpi image file is way larger in size than a 72 dpi file
I don't think I have ever created or used an image more than 96dpi

Maybe a wider slider range would help get the image to the proper scale?
300% would do the trick for 72 dpi images

**Comment by EL34xyz** [comment]
Jut as a test, I took that same Fender layout diagram that was 72 dpi and converted it to 200 dpi
It came out the correct size in DIYLC

**Comment by bancika** [comment]
yup

**Comment by EL34xyz** [comment]
How about the 300% slider to adjust the size?

Many people do not know how to create a 200 dpi image
Most of the amp guys will be getting layout diagrams from a web page and those images will be 72 dpi images

**Comment by daturach** [comment]
Faced that issue as well, did not know exactly where it was coming from. I used Inkscape to resize at the original dimension and imported into DIYLC.

**Comment by EL34xyz** [comment]
I find it hard enough to get people to do even the simplest of computer operations.
So telling someone to convert images to 200 dpi is next to impossible for most people I deal with.

**Comment by bancika** [comment]
ok, will increase the range to 500%
