### ISSUE TITLE
Tracks covered by shapes highlighted

### ISSUE THREAD

**Issue by SlyWink** [bancika/diy-layout-creator#441]
Hello,
First of all, great piece of software.
I consider using shapes and dots to create specific components for my projects.
When I probe a Vero Board using the Highlight Connected Areas functionality, all the tracks covered by a shape are highlighted.
According to me, a shape is not a conductive material and thus should not interfere with tracks.
Am I wrong or is this a bug ?
SL

**Comment by bancika** [comment]
a quick test shows that it works as expected, I have two traces and a shape that joins them, but highlight catches only one side at a time. Do you have an example?

![image](https://user-images.githubusercontent.com/11462281/53605179-f6126c80-3bb6-11e9-911f-58ac0d8aec74.png)

**Comment by SlyWink** [comment]
Here is an example :
![diy example](https://user-images.githubusercontent.com/24624623/53605386-ab452480-3bb7-11e9-9ee2-f77e96edfee0.png)

**Comment by bancika** [comment]
hmm, are you using one of recent versions? I can't reproduce and don't see anywhere in the code what might cause it, Here's the same example

![image](https://user-images.githubusercontent.com/11462281/53605781-d714da00-3bb8-11e9-926c-6f0110055ec7.png)

**Comment by SlyWink** [comment]
This is strange.
I have created a new board like yours and the behavior is as expected.
But the trouble still exists in my previous test (si attached zip file)

[testdiy.zip](https://github.com/bancika/diy-layout-creator/files/2917336/testdiy.zip)

**Comment by bancika** [comment]
I got it. It has nothing to do with shapes. There's a bug with copper traces that makes any component that gets rendered after them conductive :) If you remove copper trace from the layout it will work fine. I'll fix for 3.55
