### ISSUE TITLE
Pasted building block different from original drawing

### ISSUE THREAD

**Issue by SlyWink** [bancika/diy-layout-creator#442]
Hello,
This looks like issue #388, to which I have added a comment with an attached file, but as it is closed I am not sure you will read it.
I made a simple drawing with a shape and some dots over it, then created a building block from these parts.
When I paste the building block, several dots seem to be under the shape and thus do not appear.
See attached zip file. (the left drawing is the original one, the right one is a building block).
SL
[bb_test.diy.zip](https://github.com/bancika/diy-layout-creator/files/2922985/bb_test.diy.zip)

**Comment by bancika** [comment]
please check the latest version
