### ISSUE TITLE
Z-order still not retained for building block

### ISSUE THREAD

**Issue by SlyWink** [bancika/diy-layout-creator#444]
Hello,
Following issue #442, I tested version 3.55.1
The problem still remains ; in the screenshot, the left drawing is the original one, the right one is a building block.
SL
![capture du 2019-03-04 21-18-38](https://user-images.githubusercontent.com/24624623/53760615-beac0480-3ec3-11e9-9653-dfd6a0d19ff5.png)

**Comment by bancika** [comment]
please try 3.55.1 again

**Comment by SlyWink** [comment]
Tested after having deleted the .diylc directory. Seems to work now ;o)
![image](https://user-images.githubusercontent.com/24624623/53913673-26955300-405c-11e9-8a9c-77aea6cd0293.png)
