### ISSUE TITLE
Feature Request: Separate Visible Grid and Snap to Grid sizes

### ISSUE THREAD

**Issue by FentonBresler** [bancika/diy-layout-creator#446]
Having a small snap to grid size is essential but the small visible grid that accompanies it is not useful as a solid reference for seeing things at a glance. 

Being able to have a grid of a particular size for a quick and easy visible reference and a separate smaller snap to grid size for precise placement relative to the larger visible grid would be a great addition.

This could be implemented in a number of ways, from a bold large grid along with a faded smaller "snap to grid" grid, or a large grid as a simple dot every division and then squares for the snap to grid subdivisions. Or perhaps even visible dots or squares and an invisible "snap to grid" grid.

**Comment by JollyJimmy** [comment]
![Screen Shot 2019-03-12 at 5 22 47 PM](https://user-images.githubusercontent.com/776573/54217236-8623b080-44eb-11e9-9a24-c23a50f25618.png)

Here's a example with a dotted grid reproducing the 100 thou divisions in the top and side ruler bars and the square snap to grid set to 25 thou. I currently use this as a template using dots from the connectivity menu, but it would be a brilliant to have a native option. The setup for this workaround is a little tedious but overall it saves me a lot of time. Makes part placement that little bit easier and faster.

**Comment by bancika** [comment]
How about this solution. I added "Dot Spacing" property that is expressed in grid spacing units. When set to 1 (default), nothing happens. But you can set it to a positive integer number and then it becomes active.

![image](https://user-images.githubusercontent.com/11462281/77781771-6871ac80-7056-11ea-84d1-896b89183e77.png)

**Comment by bancika** [comment]
this feature will go out with 4.1.0 version. Hope you'll like it :)

**Comment by FentonBresler** [comment]
This looks like just the thing, wow! Many thanks!
