### ISSUE TITLE
Cannot Move Any Items - Nothing is Locked

### ISSUE THREAD

**Issue by gheorge77** [bancika/diy-layout-creator#449]
For whatever reason I cannot move anything once it is placed on the grid.  I am running on MacOSX 10.14.3. Hopefully this is a simple solution that I just can't figure out. Thanks!

-Ian

**Comment by bancika** [comment]
I cannot say without more information. Are you starting from a blank layout? Do you have "highlight connected area" mode turned on? In that mode you cannot move anything but the cursor is changed to crosshairs to indicate that something's different.

**Comment by gheorge77** [comment]
Thanks! What an embarassing mistake!

**Comment by bancika** [comment]
I'll make it show the information in the status bar while in that mode, to make it harder to miss :)
