### ISSUE TITLE
(MacOS) Components missing from 3.56 to 3.57

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#452]
After launching v3.57 on MacOS, there is only a single tab in the Toolbox (both in Tabbed Toolbar and Searchable Tree) - "Recently Used." All other component tabs are missing. Checked back to v3.56 and the Toolboxes are available.

Reproduced on MacOS Mojave 10.14.3

**Comment by bancika** [comment]
fixed the build, please try again
