### ISSUE TITLE
The pins of the super switch component are different from the real ones.

### ISSUE THREAD

**Issue by glukash** [bancika/diy-layout-creator#453]
Are the pins of a super switch different from the actual ones?
![superswitch](https://user-images.githubusercontent.com/3684876/54959374-26042400-4f59-11e9-8079-1d4a60c7adc7.jpg)

**Comment by bancika** [comment]
good catch, thanks. Will fix for 4.1.0

**Comment by neildferguson** [comment]
Please remove me from this mailing list, after multiple attempts I cannot unsubscribe thanks
