### ISSUE TITLE
DIP numbering mirroring

### ISSUE THREAD

**Issue by julessouren** [bancika/diy-layout-creator#457]
If a trace-side view of a board with a DIP IC is created (i.e. a mirrored view of the component side), then the pin numbering on the IC is not mirrored.

In other words, a DIP IC cannot be modified such that it appears to be viewed from through the board, and have its pin numbering shown correctly (mirrored).

I find this feature useful for debugging boards, by immediately identifying correct pin numbers on the trace side, without having to think mirrored.

**Comment by bancika** [comment]
would it be sufficient to add two more options here called "DIP (Mirrored)" and "Connector (Mirrored)" that would show the numbering mirrorer?

![image](https://user-images.githubusercontent.com/11462281/77580456-58ce5880-6edc-11ea-9fa1-db51375e75de.png)

**Comment by bancika** [comment]
added for 4.5.0
