### ISSUE TITLE
Highlight Connected Areas tool is not working properly.

### ISSUE THREAD

**Issue by starpath07** [bancika/diy-layout-creator#458]
[log-2019-04-19 04.16.36.txt](https://github.com/bancika/diy-layout-creator/files/3098504/log-2019-04-19.04.16.36.txt)

Highlight tool is showing unrelated (and unconnected) stripboard tracks as connected. Note the attached screen grab where I have removed the link between rows V and W. The ground plane should stop being highlighted from row W downwards. This is a proven design which I have built and is functioning properly. 
![2019-04-19](https://user-images.githubusercontent.com/36608059/56430930-5923a400-62c8-11e9-8a4d-07435c5a349c.png)

**Comment by jovi2k** [comment]
It seems that when a jumper length is even, the connected points are not only the jumper ends, the middle point is also connected with them. This is not an issue with hookup wire, so you can edit hookup wire with two points and save it as variant and use it afterwards.

Jumper with even length
![jumper_even](https://user-images.githubusercontent.com/26671486/57178704-f0662b00-6e74-11e9-8a50-e62512a79a25.jpg)

Jumper with odd length
![jumper_odd](https://user-images.githubusercontent.com/26671486/57178708-f78d3900-6e74-11e9-9089-0fe87b257cc7.jpg)

Hookup wire with even length
![hookup_even](https://user-images.githubusercontent.com/26671486/57178739-6074b100-6e75-11e9-9b90-36289563747f.jpg)

Hookup wire with odd length
![hookup_odd](https://user-images.githubusercontent.com/26671486/57178740-6cf90980-6e75-11e9-9d12-67e1466d3f50.jpg)

**Comment by csj2k** [comment]
I also have this issue.

**Comment by bancika** [comment]
found what it is...will be included in the next version.
