### ISSUE TITLE
Humbucker pickup screws pole pieces show as rods

### ISSUE THREAD

**Issue by gtranter** [bancika/diy-layout-creator#462]
Version 3.57.0.

Humbucker Pickup (all variants).

If you select "screws" for "pole pieces 2" they show as rods unless "pole pieces 1" is also set to "screws".

**Comment by stoneattic** [comment]
I see the same issue.  Pole Pieces 2 only display screws when both sets of pole pieces are set to screws.  No combination of choices will display screws on Pole Pieces 2 and rods on Pole Pieces 1.

**Comment by bancika** [comment]
fixed for 4.1.0
