### ISSUE TITLE
Cutting and pasting components ruins my numbering system

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#465]
I sometimes lay out a schematic in DIYLC, and then I copy/cut and paste components from the schematic to my board layout, and ideally I would like to maintain my component numbering system.  

However, the new improvement that renumbers components after I copy/cut and paste messes up my workflow: 

_"[Improvement] Assign a new name for pasted component if the project already contains components under that name"_ 

Is there any chance to make this feature optional?

**Comment by bancika** [comment]
Included for 4.0.1 version that will be out soon.
