### ISSUE TITLE
stripboard track break still active after removing in HIGHLIGHT mode. Requires shifting the board itself to correct itself.

### ISSUE THREAD

**Issue by starpath07** [bancika/diy-layout-creator#471]
[log-2019-08-06 01.57.02.txt](https://github.com/bancika/diy-layout-creator/files/3489246/log-2019-08-06.01.57.02.txt)
![20190809_213454](https://user-images.githubusercontent.com/36608059/62826331-f6794f80-bbb9-11e9-8789-b99603715fec.jpg)

Problem is in stripboard mode, with the board locked or not. When using HIGHLIGHT mode, green highlight is detecting a previously deleted or moved or cut track break as still being there and would not continue highlighting the track beyond that point. This happens from both sides of the removed break. This can be seen in the picture under the "100K" text and to the immediate left of the 100nF ceramic. The track break visible was originally in place where the descending wire link joins the track, and was moved two places to the left, however, HIGHLIGHT is still treating the layout as if the break was still there. The only way this could be rectified is by moving the board about and returning it back in place, after which, the HIGHLIGHT tool works properly.

**Comment by bancika** [comment]
fixed for 4.1.0
