### ISSUE TITLE
diy-layout-creator is only backward compatible till DIYLC Gen3 v55.1 only. (not v56 or v57)

### ISSUE THREAD

**Issue by MadiI-Hup** [bancika/diy-layout-creator#474]
Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates.
* Make sure that you are running the latest version of DIYLC.

**Comment by bancika** [comment]
Hi,
do you have an example? Otherwise it could mean anything.
Thanks

**Comment by MadiI-Hup** [comment]
Hi
Please find attach is a sample layout that opens normally with v. 55.1 and earlier.
If you want an illustrated pictures, let me know.
By the way, thank you for the great product.

Thanks
madi


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bancika** [comment]
hmm, couldn't find the file, can you please try to upload it through github (vs though email)?

**Comment by MadiI-Hup** [comment]
Hi,
See The attached zip file

[SIO-project_mini_3a.zip](https://github.com/bancika/diy-layout-creator/files/3694520/SIO-project_mini_3a.zip)
