### ISSUE TITLE
File menu reacts slow

### ISSUE THREAD

**Issue by stevensloane** [bancika/diy-layout-creator#477]
When I go to open a file on  Win 10 version 57.0 the File menus reacts slow. If I try to open a file, import, save or use any of the functions under the file menu it take at least 10 seconds or more before the box opens to make my selection.

**Comment by stevensloane** [comment]
When I go o the recent file files it opens normal with no problems

**Comment by bancika** [comment]
Is it slow only for the File menu or for others too, like Config?

**Comment by stevensloane** [comment]
It was just the file menu but it’s no longer an issue since in reinstalled windows

**Comment by bancika** [comment]
Odd, could be something about that instance of windows or Java.
