### ISSUE TITLE
Triode doesn't mirror only rotates

### ISSUE THREAD

**Issue by pixelwaster** [bancika/diy-layout-creator#482]
The triode schematic symbol doesn't mirror horizontally (Alt-H), it rotates 180. Using Alt-V and nothing changes. 

If you try to mirror horizontally after mirror horizontal; nothing changes - the part stays rotated. Menu or short-cut keys gives the same results. 

Using the "edit selection", in the Orientation drop down it says 180 degree clockwise after Alt-H.

Logs attached
[log-2019-12-02 06.26.14.txt](https://github.com/bancika/diy-layout-creator/files/3913944/log-2019-12-02.06.26.14.txt)

**Comment by bancika** [comment]
Fixed for 4.2.0
