### ISSUE TITLE
symbols

### ISSUE THREAD

**Issue by KENTUCKYTUKKER** [bancika/diy-layout-creator#485]
During my first project using DIYLC I'm missing the following aids:

1.possiblity to rotate the grounding symbol upside down
2. possibility to add socket connection numbers to tube symbols

**Comment by KENTUCKYTUKKER** [comment]
numbering of tube symbols soved already by myself

**Comment by bancika** [comment]
Ground symbol orientation is still not supported. Will add to the queue.

**Comment by KENTUCKYTUKKER** [comment]
Hello Bane,

I solved the other issue about adding numbers to the tube symbols 
already.
------ Origineel bericht ------
Van: "Bane Stojkovic" <notifications@github.com>
Aan: "bancika/diy-layout-creator" 
<diy-layout-creator@noreply.github.com>
CC: "KENTUCKYTUKKER" <r.mikkers@home.nl>; "Author" 
<author@noreply.github.com>
Verzonden: 24-12-2019 14:11:18
Onderwerp: Re: [bancika/diy-layout-creator] symbols (#485)

**Comment by bancika** [comment]
Added ground symbol rotation for 4.0.1
