### ISSUE TITLE
DIYLC won't open .diy files - old or new

### ISSUE THREAD

**Issue by king-custom-electonics** [bancika/diy-layout-creator#487]
I've just managed to make the latest version of DIYLC work on my Mac Book. When I try to open up a .diy file (I have hundreds) it shows an empty folder. Even if I create and save a new file the folder still shows as empty. It's not empty. Any ideas?

**Comment by bancika** [comment]
can you please upload the log file? it should be in user folder under .diylc/logs

**Comment by orlandwright** [comment]
Hi, I'm experiencing the same issue on Mac Catalina. I can't find directory .diylc to pull any logs.

**Comment by orlandwright** [comment]
Some more info for you. Files will open correctly from the "recent files" menu option. Trying to open the same files by clicking on them results in a blank board. Trying to find them via "open" results in blank directories.

**Comment by bancika** [comment]
Here's where to find the logs. Just replace "admin" with your username.

![image](https://user-images.githubusercontent.com/11462281/77806465-0f6d3d00-7085-11ea-8cd3-994d2a9794b3.png)

**Comment by king-custom-electonics** [comment]
Thank you! I couldn't find them (I guess you knew that). It turned out to a permissions issue with OSX. I've never had this issue but suddenly DIYLC lost access to the disk drive. Remembering my IT days (mid-90s) I thought to check permissions. This is a problem you may not encounter again. My issue seems to have been a fluke.
Thanks for getting in touch!
Best,Alex
    On Friday, March 27, 2020, 06:46:30 PM EDT, Bane Stojkovic <notifications@github.com> wrote:  
 
 


Here's where to find the logs. Just replace "admin" with your username.

**Comment by bancika** [comment]
Great!
