### ISSUE TITLE
Auto-create pad don't work properly

### ISSUE THREAD

**Issue by animalejo** [bancika/diy-layout-creator#489]
i use the 3.57 version

the option of auto create pad, doesn't work properly 

video link: [https://www.dropbox.com/s/7newrz69gsvu34r/IMG_1478%20%281%29.mp4?dl=0](https://www.dropbox.com/s/7newrz69gsvu34r/IMG_1478%20%281%29.mp4?dl=0)

in the latest versions this works well
this was very helpful so please mr bancika help us ! :D

**Comment by bancika** [comment]
Fixed for version 4.01
