### ISSUE TITLE
damage file

### ISSUE THREAD

**Issue by benwadub** [bancika/diy-layout-creator#491]
hi, when I try to instal diilc on Mac the Mac tel me that the file is damaged, I authorized third party app

**Comment by stdin** [comment]
Same issue here

**Comment by proddy** [comment]
been covered multiple times in previous issues. do a search

**Comment by bancika** [comment]
Does this version work for you?

[diylc-4.0.1-osx.zip](https://github.com/bancika/diy-layout-creator/files/4374216/diylc-4.0.1-osx.zip)

**Comment by cenobitedk** [comment]
Do this
https://www.youtube.com/watch?v=6fqzb4qpgcs
or this
https://www.youtube.com/watch?v=3py0kgq95Hk
