### ISSUE TITLE
desktop icon in the ZIP -- not really an issue

### ISSUE THREAD

**Issue by peterjosvai** [bancika/diy-layout-creator#492]
hi, 
since we can launch DIYLC 
from a "desktop launcher" (talking about Linux, but must be similar in Micro$oft environment, too), 
it is a logical step to give it an icon, too :)

which could be created from the splash.png by resizing it to 48x48, for example...
and it could be added in the next zip file...

(I attach what I've just made like that)
![DIYLC](https://user-images.githubusercontent.com/13543101/73270666-64a0e580-41df-11ea-807c-769635dfd160.png)

**Comment by bancika** [comment]
Hi,
how do I create a desktop launcher for an app on Linux? Do you have experience with that?
I made a dedicated icon that could work.
Cheers

![icon5](https://user-images.githubusercontent.com/11462281/77350099-4fa68580-6d3c-11ea-8ba7-fcfcac19056d.png)

**Comment by bancika** [comment]
Including a folder with the app and DIY file icons in various formats. This will be out with 4.0.1

![image](https://user-images.githubusercontent.com/11462281/77580110-b8783400-6edb-11ea-9ba3-2e799829c4aa.png)
