### ISSUE TITLE
Zoom with touchpad on Mac is broken

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#501]
With DIYLC open, hold down command key while scrolling in/out on the touchpad. 
You will notice that the interface appears to zoom in and out randomly without any real correspondence to user interaction. 

Reproduced on: Macbook Air w/ macOS Mojave 10.14.6

**Comment by bancika** [comment]
I don't think there's apple touchpad support in java jet

**Comment by htor** [comment]
correct me if i'm wrong, but doesn't java support touchpad movement regardless of platform? or do you  also, it seems to me the movement gets messed up on macos because its trying to pan in x y while at same time zooming?

**Comment by bancika** [comment]
I know nothing about macs really, never worked on one :)

**Comment by bancika** [comment]
should be fixed. Pinch zooming works on all platforms now. Ctrl +/- as well.
