### ISSUE TITLE
Download blocked by Google Chrome:

### ISSUE THREAD

**Issue by BiffDebris** [bancika/diy-layout-creator#509]
diylc-4.1.0-win.exe is not commonly downloaded and may be dangerous. 
Uncommon: You tried downloading an unfamiliar and potentially dangerous piece of software.
We've found that the website you tried to download the file from has been known to distribute malware.

**Comment by bancika** [comment]
I cannot control what Google Chrome does. You can still choose to keep the file if you click on the arrow next to Discard button
