### ISSUE TITLE
I have a suggestion

### ISSUE THREAD

**Issue by stinga11** [bancika/diy-layout-creator#520]
Greetings, is it possible that I add these types of rectification tube (5Y3) (GZ34) to the schematic drawings?

https://www.thetubestore.com/lib/thetubestore/schematics/Fender/Fender-64-Vibroverb-Custom-Schematic.pdf

https://www.thetubestore.com/lib/thetubestore/schematics/Fender/Fender-57-Deluxe-Schematic.pdf

**Comment by stinga11** [comment]
I try to draw them and so I use them. Here I leave you my attempts.
[Rectifier Tubes.zip](https://github.com/bancika/diy-layout-creator/files/4465109/Rectifier.Tubes.zip)

**Comment by EL34xyz** [comment]
This might help Bancika
Pins 2, 4 , 6 and 8 are the only pins used on a standard 8 pin tube socket for all the common tube rectifiers.

![TubeRectifier](https://user-images.githubusercontent.com/16766383/79068210-3fc2f700-7c93-11ea-8613-a668c41e7a13.png)

**Comment by bancika** [comment]
Added duo-diode symbol

![image](https://user-images.githubusercontent.com/11462281/79105973-ed0c3c80-7d71-11ea-860f-49618d2eb306.png)

**Comment by stinga11** [comment]
Thank you !!!
