### ISSUE TITLE
Resistor leads are not showing when tightly bent

### ISSUE THREAD

**Issue by HelixOnGit** [bancika/diy-layout-creator#524]
When inserting a resistor (207 shape) across two rows (most thight bend of leads) the leads are not displayed. 
![2020-04-21 224511](https://user-images.githubusercontent.com/62563222/79912122-d1fc9500-8421-11ea-9edc-79cccb40304e.jpg)

Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates.
* Make sure that you are running the latest version of DIYLC.

**Comment by HelixOnGit** [comment]
[log-2020-04-21 10.24.14.txt](https://github.com/bancika/diy-layout-creator/files/4512535/log-2020-04-21.10.24.14.txt)

**Comment by bancika** [comment]
will fix
