### ISSUE TITLE
Wishlist: Rotary Switch

### ISSUE THREAD

**Issue by HelixOnGit** [bancika/diy-layout-creator#525]
Please include higher number of throw and different numbers of poles (3P4T, 1P12T, 1PxT etc.) for the rotary switch

**Comment by bancika** [comment]
The rotary switch I added in this iteration is the large one used in amp building. Those have only few positions. This would need a new component type of component or maybe even two.

![image](https://user-images.githubusercontent.com/11462281/79957541-00aa5800-8482-11ea-8160-141de05b0f33.png)
![image](https://user-images.githubusercontent.com/11462281/79957554-056f0c00-8482-11ea-81d0-a0cdd6008ecb.png)

**Comment by HelixOnGit** [comment]
I think these types are pretty much the most popular in synth diy community (quite similar to your first picture)
https://lorlinelectronics.co.uk/catalogue?filter_switch-category=rotary-switches
They also come as solder lug/pcb mount terminals. 

I understand that you maybe aim at a different target audience though.

**Comment by bancika** [comment]
These were finally added in 4.30, 4 types of sealed and 4 types of open switches.
