### ISSUE TITLE
Separating twisted-pair wires

### ISSUE THREAD

**Issue by BiffDebris** [bancika/diy-layout-creator#528]
Hello Mr. bancika- First off, I finally got the latest version of diylc to run. I deleted everything (all files of the program, .diylc, registry, etc.), shut off Windows Defender and the firewall. Installed and made exclude from scan option, and !!Ta-dah!! It works!  I will send the log files to you if needed.

My next question though is how do you separate twisted-pair wires? I am trying to do a re-wiring of a Strat copy and I need one wire to go to volume casing, and other goes to 5-way switch. 

It just came to my mind that it would be something to have a shielded cable component with up to 4 wires that's usually what humbuckers have nowadays. Let me get used to this program and maybe I will give it a whirl and make one.

Thank you for reporting issues and contributing ideas and features to DIYLC repository!

Before you proceed, please read the following:

* If you are reporting a bug, please attach the latest application log file together with description of steps that lead to the issue. They can be found in the user directory under `.diylc/logs` directory. On Windows 7 and later, it's located in `c:/Users/<your username>/.diylc/logs`. On Linux and MacOS, it's typically in `/Users/<your username>/.diylc/logs`.
* If you are having issues starting the application under MacOS, make sure that 3rd party apps are allowed on your Mac. This document covers how to do it - https://support.apple.com/en-us/HT202491.
* Try to look for similar unresolved issues that are already reported to avoid duplicates.
* Make sure that you are running the latest version of DIYLC.

**Comment by bancika** [comment]
The only way is to delete the twisted pair and replace with separate instances of hookup wire.
Glad to hear that it works!
