### ISSUE TITLE
Wishlist : micro switch and quartz

### ISSUE THREAD

**Issue by Fatche2** [bancika/diy-layout-creator#530]
Hi Branislav,

Please add 

microswitch like those ones : https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSRZiFqj3aNhobzpfKs1Ucd2mehsxBvjXP_lSxwVx_LV-2awQuZiCdLY7_UCDJIpCzSOoe-77mn&usqp=CAc

quartz : https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSXQcTrNHiZJLCDCWV8OqiW20c2ZfoWAth4RJIzknldult4msoYfxaN0-XTmwEhem5lqry9PPzu&usqp=CAc

**Comment by bancika** [comment]
quartz added in 4.7.0

**Comment by bancika** [comment]
micro switch added for 4.13
