### ISSUE TITLE
Radial Capacitors are not configured properly in v4.5.0

### ISSUE THREAD

**Issue by abie-mixxx** [bancika/diy-layout-creator#531]
I just upgraded to v4.5.0 (OS X) and now all the radial capacitors (orange) are the same size and layout as the axial capacitors (yellow), spanning 6 rows on a vero board instead of the usual 2.

**Comment by bancika** [comment]
this was fixed for 4.6.0

**Comment by abie-mixxx** [comment]
Awesome! Love the program, thanks for everything you put into it!
