### ISSUE TITLE
Wishlist: Middle Mouse Button Pan

### ISSUE THREAD

**Issue by thewool** [bancika/diy-layout-creator#540]
Press and hold Middle Mouse Button to Pan and Middle Mouse Button scroll to Zoom

**Comment by EL34xyz** [comment]
On my W10 system, clicking the middle mouse button lets me pan all directions by moving the mouse.
It brings up the four way move cursor when I click the middle mouse button

![mouse1](https://user-images.githubusercontent.com/16766383/82729723-d5589a00-9cc7-11ea-8bd2-6f8ad1fd98f2.png)
