### ISSUE TITLE
diylc-4.7.0 Pinheaders Can´t be rotated 

### ISSUE THREAD

**Issue by abel2b** [bancika/diy-layout-creator#541]
PCB mounted male Pin Headers can´t be rotated (Popup :Some components cannot be rotated) 

[log-2020-05-16 10.20.12.txt](https://github.com/bancika/diy-layout-creator/files/4638470/log-2020-05-16.10.20.12.txt)

**Comment by bancika** [comment]
you can still rotate them by double click and change orientation

**Comment by abel2b** [comment]
yes and also while placing with right mouse click, but once placed on board it´s much more convenient to use CTRL+Right to rotate.. 

Thank you for your time..

**Comment by bancika** [comment]
Done for 4.9.0
