### ISSUE TITLE
Adjust font size Property  in Components

### ISSUE THREAD

**Issue by StephenCohrs** [bancika/diy-layout-creator#543]
Cannot change the font size in components. e.g. the 25mm potentiometer default font size is too small and it doesn't seem to be a property of the device. Resetting the project default size works but then some of the smaller components font is too big and overruns the borders. Can they be set differently? 
IMO, the default is good but you need to override in some cases - bigger or smaller.
Is there a workaround?

**Comment by bancika** [comment]
No workaround at the moment

**Comment by bancika** [comment]
Actually, the workaround is to have the component label empty and then overlay a "Label" component with the desired font size. Thinking about a permanent solution.

**Comment by bancika** [comment]
will implement in 4.13
