### ISSUE TITLE
Undo is slow

### ISSUE THREAD

**Issue by TomKamphuys** [bancika/diy-layout-creator#547]
Undo takes seconds to take place.

Windows 10, V4.7.0

**Comment by TomKamphuys** [comment]
Changing the zoom factor is also slow.

**Comment by TomKamphuys** [comment]
It seems to have something to do with a dotted line. Attached you'll find a reduced example differing only in the absence/presence of a dotted line. The difference in visual feedback on a CTRL-Z is substantial.

[slowFast.zip](https://github.com/bancika/diy-layout-creator/files/4706524/slowFast.zip)

**Comment by TomKamphuys** [comment]
It looks like the dotted line is not the only thing. Removing the dotted line from my original file does not help.

**Comment by bancika** [comment]
Thanks for the info. Yes, it certainly seems to be the dotted line. I'll investigate

**Comment by bancika** [comment]
fixed for 4.13
