### ISSUE TITLE
Feature request: Mirror coordinate origin of board on Transform - Mirror

### ISSUE THREAD

**Issue by chipshorter** [bancika/diy-layout-creator#550]
If "Edit > Transform Selection > Mirror Horizontally/Vertically" is applied to a "Vero Board" or "Perf Board" it would be nice to reassign the coordinate origin.

e.g. If board has coordinate origin "Top Left", then "Mirror Vertically" would result in a coordinate origin of "Bottom Left"

**Comment by bancika** [comment]
done for 4.12
