### ISSUE TITLE
Hot Key for "Snap to Grid/Component"

### ISSUE THREAD

**Issue by dwinstonwood** [bancika/diy-layout-creator#559]
Hello, first thank you for a great piece of software (I made a Paypal contribution because I like it so much).
My issue is: it would be great if there was a Hot Key to switch between "Snap to Grid" and "Snap to Component." I use both settings continually when drawing layouts.
Or, maybe just a toggle button up on the top-right tool bar like you have for "Rotate" and "Mirror," etc. That might even be better.
Thank you!
David

**Comment by bancika** [comment]
Thanks for the donation. I'll add the request to the queue.
Cheers

**Comment by bancika** [comment]
Added in the toolbar for 4.12.
