### ISSUE TITLE
SPDT switch symbol error

### ISSUE THREAD

**Issue by PhilipStolz** [bancika/diy-layout-creator#560]
The visualization of the SPDT switch looks wrong (see screenshot). I would have expected something with 3 pins instead of 15.

![SPDTBug](https://user-images.githubusercontent.com/68202691/87255789-154d2980-c48e-11ea-99a9-dd908bd61366.png)
[log-2020-07-12 09.56.46.txt](https://github.com/bancika/diy-layout-creator/files/4909390/log-2020-07-12.09.56.46.txt)

**Comment by EL34xyz** [comment]
I am not seeing that
You are showing a **5**PDT, not a SPDT

![Image1](https://user-images.githubusercontent.com/16766383/87436624-48d9a200-c5bb-11ea-9442-4c13e6e234d8.png)

**Comment by bancika** [comment]
Yup.
