### ISSUE TITLE
Must JDK 1.6 on Win10？

### ISSUE THREAD

**Issue by bh1rio** [bancika/diy-layout-creator#576]
Is it Must JDK 1.6 on Win10？
![微信截图_20200907143238](https://user-images.githubusercontent.com/12414463/92355905-c7fcd980-f117-11ea-8b72-bbf14f5e43d2.png)

there is JDK 11 on my Win10......
![微信截图_20200907143640](https://user-images.githubusercontent.com/12414463/92355918-ccc18d80-f117-11ea-8f16-73f2e5265bf3.png)

**Comment by bancika** [comment]
you could try to run it directly from the console using java 11, the command should be something like this

java -jar diylc.jar -Xms512m -Xmx1024m -Dorg.diylc.scriptRun=true -Dfile.encoding=UTF-8

**Comment by bh1rio** [comment]
there is a messagebox behind the welcome.
![微信截图_20200907171154](https://user-images.githubusercontent.com/12414463/92370766-50d24000-f12d-11ea-9703-76b41a615ec4.png)
console like this
![微信截图_20200907171207](https://user-images.githubusercontent.com/12414463/92370808-5e87c580-f12d-11ea-9233-41ce875eb187.png)

**Comment by htor** [comment]
this has probably been discussed before, but why not ship a specific JRE with the application, so the required java version is always controlled by the app maintainer and not the users? this way the JRE shipped is the one used to run DIYLC and the user don't even need the install any JRE.  

i'm no active java developer but i heard that bundling the JDK/JRE into the app distributables could perhaps solve these version problems?

i may be wrong, though!

**Comment by htor** [comment]
here is some more information if you would go down that route:
* https://docs.oracle.com/javase/7/docs/technotes/guides/jweb/packagingAppsForMac.html#bundle_jre (mac)
* https://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html

**Comment by bancika** [comment]
Figured out a way to include JRE in windows installation as well, closing.
