### ISSUE TITLE
[Mac OS] Command key shortcuts broken, working only intermittently

### ISSUE THREAD

**Issue by iiimonfiiire** [bancika/diy-layout-creator#577]
Running DIYLC newest version 4.8.0 on Mac OS (10.14.6)

**Description:**
Keyboard shortcuts using Command key are broken - sometimes they work, sometimes they do not. Not sure what specific reproduction steps need to be taken, as it happened to me quite often after simply working with a .DIY file. Commands that were working/not working intermittently:
Copy [Command + C]
Paste [Command + V]
Edit component settings [Command + E]

[log-2020-09-10 10.01.42.txt](https://github.com/bancika/diy-layout-creator/files/5200040/log-2020-09-10.10.01.42.txt)

**Comment by bancika** [comment]
Is it the same when you switch from the component tree to the toolbar (from Config menu)?

**Comment by bancika** [comment]
assuming it was fixed with the new component tree.  Please comment if still an issue
