### ISSUE TITLE
Variants are mispositioned when placing

### ISSUE THREAD

**Issue by pmfawcett** [bancika/diy-layout-creator#578]
Another easy-to reproduce bug (from the 4.9.0 preview)

I created a variant of an eyelet.  Now whenever I select and try and place an instance of this variant, the place where the object is drawn differs from where the placement bullseye is drawn!  Saving different variants will result in different (seemingly random) offsets.  It may have to do where the original object was placed at the time the variant is created?
The attached image shows an attempt to place an eyelet variant instance. Note the green dot is not coincident with the ghost outline of the eyelet to be placed.

![DIYLC6](https://user-images.githubusercontent.com/28827526/92768070-aabd4a80-f365-11ea-9e2e-609e4274fc5e.png)

**Comment by bancika** [comment]
Good catch, yes this is a regression bug in 4.9.0.
