### ISSUE TITLE
Black screen with Windows 10

### ISSUE THREAD

**Issue by chemical-oli** [bancika/diy-layout-creator#580]
[log-2020-09-14 12.04.37.txt](https://github.com/bancika/diy-layout-creator/files/5215317/log-2020-09-14.12.04.37.txt)
Hi im having problems with Windows 10, the main screen is black and the "mid-scroll" arrow appears in menu items and across the black screen.  Appears not to be rendering properly.
![diylc](https://user-images.githubusercontent.com/37980261/93031109-3104b580-f620-11ea-9d46-ca4255c22343.jpg)

Using Java runtime environment 1.8.0_261

Link to [screenshot](https://imgur.com/a/aqliFou) just in case

**Comment by bancika** [comment]
Please try toggling "Hardware Acceleration" setting from the Config menu.

**Comment by chemical-oli** [comment]
Thanks this seems to have fixed the problem.

**Comment by bancika** [comment]
Cool! Seems like it's not compatible with all graphic cards or maybe drivers.
