### ISSUE TITLE
Project cloud "replace project" fails

### ISSUE THREAD

**Issue by pmfawcett** [bancika/diy-layout-creator#591]
The project cloud -> manage my uploads -> replace project seems to fail.  The project file is not actually replaced, as confirmed by both restarting the DIYLC application, and by downloading the project on a separate computer.  I'm not certain, but this bug may only happen when you do not change the filename when attempting to replace.   At this time it is necessary to delete the old project and reupload the replacement as new.  Note that replacing the project file also gets rid of all of the project information and description that it typed in, and this is not a desirable behaviour... most of the time one wants to correct a minor error that has been found, not start from scratch.  Right now there is actually hardly any benefit to replacing vs. just deleting and making a new project.

**Comment by bancika** [comment]
Fixed for 4.11.0
