### ISSUE TITLE
Menubar destroy in german language

### ISSUE THREAD

**Issue by HaraldRau** [bancika/diy-layout-creator#602]
Hello,
In the German language there is a problem with the display in the menu bar. The desire for coffee destroys the menu bar.

[log-2020-12-09 12.57.09.txt](https://github.com/bancika/diy-layout-creator/files/5665696/log-2020-12-09.12.57.09.txt)

![Leiste_defekt](https://user-images.githubusercontent.com/47145786/101627647-f2b04400-3a1e-11eb-8d14-7e7ddd4a3275.png)

Thank You for your perfect Work!

**Comment by bancika** [comment]
Hi Harald, thanks for the heads-up and thanks for the solution! I have included it in the next release.
And thank you for the coffee, it's highly appreciated!

**Comment by HaraldRau** [comment]
Hello, no problem. Enjoy it!
It's a great program. I used it to design the circuit board for my
simple tube amplifier.

Am Mittwoch, den 09.12.2020, 05:49 -0800 schrieb Bane Stojkovic:
