### ISSUE TITLE
Lugs misplaced when rotating Neutrik jack other than default

### ISSUE THREAD

**Issue by pmfawcett** [bancika/diy-layout-creator#610]
4.13.0 / Win 7

There is a problem with rotation of certain objects under 4.13.0.  I'm not sure how general may be, but I discovered the problem with the Neutrik jacks. The lugs are misplaced upon rotation. See attached image.
![Rotate_bug](https://user-images.githubusercontent.com/28827526/103106574-a101df00-4604-11eb-8ae6-b287082fcba1.png)

**Comment by bancika** [comment]
fixed
