### ISSUE TITLE
Copied group becomes ungrouped

### ISSUE THREAD

**Issue by rsmilward** [bancika/diy-layout-creator#621]
Latest DIYLC (4.15.1) under Win10 (2004). Made a custom group of Vero-board strips, grouped them together, copied & pasted them, but the copy is ungrouped. Duplicating instead of copying produces the same result.

**Comment by EL34xyz** [comment]
I tested this in 4.17
The copied group is ungrouped when pasted

I noticed this a long time ago but forgot that it does not work until I saw your post

**Comment by bancika** [comment]
Implemented for 4.19

**Comment by EL34xyz** [comment]
Thanks Bane
