### ISSUE TITLE
Wishlist - keyboard shortcut to switch between "highlight connected areas" active and not-active

### ISSUE THREAD

**Issue by aabill2** [bancika/diy-layout-creator#627]
I frequently need to do this. Or better still how nice it would be to have user-configurable shortcuts.

**Comment by bancika** [comment]
The Alt key will temporarily toggle this setting.

**Comment by aabill2** [comment]
Aaaah superb thanks, and apologies if it's in the Help and I missed it.

Best regards
Bill Allison
   On Tuesday, 9 February 2021, 19:26:35 GMT, Bane Stojkovic <notifications@github.com> wrote:  
 
 


The Alt key will temporarily toggle this setting.
