### ISSUE TITLE
Wishlist - connectivity component: 1-core and 2-core screened cable

### ISSUE THREAD

**Issue by aabill2** [bancika/diy-layout-creator#628]
As per title

**Comment by bancika** [comment]
There's an easy workaround for this - just combine regular wires of different gauges

![image](https://user-images.githubusercontent.com/11462281/108625972-1136b080-744e-11eb-9bf8-1f03acdddac0.png)

**Comment by aabill2** [comment]
Than you, much appreciated

Bill 

   On Sunday, 21 February 2021, 13:07:52 GMT, Bane Stojkovic <notifications@github.com> wrote:  
 
 


There's an easy workaround for this - just combine regular wires of different gauges
