### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mhuss99** [bancika/diy-layout-creator#643]
As a first test of the program, I created a long board that ran outside the dotted lines, and after I realized there was no way to print anything except for the section of the board inside the dotted lines, I had to do some hokey pokey to split it into two files to print (and later tape it together). This would have been much easier if the area outside the dotted lines wasn't a fixed width! (I'm used to programs like KiCad that basically place you in the center of a football field of virtual space.)

I suggest either adding the ability to scale the layout for printing, or prohibit placing components outside the printable area (or at least warn that there's no way to print outside the lines). It may say something about this in the User Guide, but who reads the whole user guide when just taking a program for a test drive? ;)

**Comment by bancika** [comment]
Canvas size is configurable, you can make it larger and then scale at the time of printing.
