### ISSUE TITLE
file icons for Mac

### ISSUE THREAD

**Issue by animalejo** [bancika/diy-layout-creator#653]
Little suggestion, maybe could use one of this icons for mac: 
https://drive.google.com/drive/folders/1lbaPO8ja-Iu6XmUj7li3nT8NVCmfWGza

In Windows the icons are different for the application and Files, in mac not so maybe could use any of this icons for files. 

Just a cliche

**Comment by bancika** [comment]
Finally included in 4.35 build, thank you!
