### ISSUE TITLE
Suggestion: Add 5/6-way rotary switch component

### ISSUE THREAD

**Issue by MedicOP** [bancika/diy-layout-creator#658]
Would be cool if 5/6-way rotary switches were added
https://www.stewmac.com/electronics/components-and-parts/switches/rotary-switches/

**Comment by KENTUCKYTUKKER** [comment]
I created my own switches. i.e. for the impedance selection, by using the "dot" and the "line" symbol. It is some little work to do but you can create any config you want

**Comment by bancika** [comment]
these were finally added, along with some other variations of rotary switches
