### ISSUE TITLE
Feature request - Autosave

### ISSUE THREAD

**Issue by justinhd** [bancika/diy-layout-creator#659]
Would it be possible to include an autosave function? I lost a lot of work when an update was applied and I was not prompted to save my open file. If an autosave function was available it would save folks a lot of rework. 
Thanks

**Comment by bancika** [comment]
There is autosave. Look for backup folder under .diylc in user directory.

**Comment by justinhd** [comment]
Many thanks Bane! Much appreciated.

Kind regards,
Justin

On 25 Jul 2021, at 12:29, Bane Stojkovic ***@***.***> wrote:

﻿

There is autosave. Look for backup folder under .diylc in user directory.
