### ISSUE TITLE
run.sh improvements

### ISSUE THREAD

**Issue by codeminkey** [bancika/diy-layout-creator#660]
run.sh is missing a 'she-bang' line, which is helpful for running it from the command line.  The first line should be "#! /bin/bash" or "#! /bin/sh" (more generic).

Also, the command line should end with '"$@"' in order to pass command line arguments to the main program.  This allows the user to double-click on project files in the file explorer to launch them.  Without this double-clicking on a project file opens diylc with a new/empty project.  The shell variable '$@' should be enclosed in double quotes to ensure that any arguments with spaces in them are properly quoted.

The full file should look like this (based on v 4.18.0-1):

    #!/bin/bash
    java -Xms512m -Xmx2048m -javaagent:lib/jar-loader.jar -Dorg.diylc.scriptRun=true -Dfile.encoding=UTF-8 -cp diylc.jar:lib org.diylc.DIYLCStarter "$@"

Thanks!

**Comment by bancika** [comment]
Thanks!

**Comment by codeminkey** [comment]
yw... thank you!
