### ISSUE TITLE
Issue with Phono Jack

### ISSUE THREAD

**Issue by Marcelo85plus1RS** [bancika/diy-layout-creator#665]
Hi, first of all, thank you for this excellent tool.
I'd like to point out this little issue with the phono jack, when you rotate it, this happens...
![Sin título](https://user-images.githubusercontent.com/89396026/130452147-690659ff-14eb-40c6-bcef-4f580e9d730d.jpg)
That's all for now, bye.

**Comment by bancika** [comment]
Fixed for 4.21.4
