### ISSUE TITLE
Cannot get backgroud to grey editing theme

### ISSUE THREAD

**Issue by visuttaja** [bancika/diy-layout-creator#671]
I need grey background for my white allergy eyes. Current  dark theme covers black font from files like this:
https://robrobinette.com/images/Guitar/5E3P_Build/5e3_Tube_Guitar_Amplifier.diy
Blue theme also messes up with black grid and hurt eyes immediately. 
I have been working on this quite a while on web pages and have found simpole solution to use just a little light grey  background which lets original black text cut through the image. Nothing else is needed.
Just simply little shade of grey as background. Color is exactly  r=170 g=170 b=170. Point is that if someone has used black font color it still can be seen very well on such grey backgourd. 
So I tried to edit those themes but it is not happening. Installation directory has config.xml which also has section for colors. 
Themes directory contains *.xml for three themes.
User directory C:\Users\<user>\.diylc has one config xml which has colors section. 
But it seems that there is also colors hardcoded in some java source because changed made in any of those given xml sections have no effect none. So there is at least four places....
I could compile the program from source but I would not like to put all my energy on it only because of need to get grey background.  Could you tell how it is choosing between those different places so I could get my grey background. I really would like to start use diylc.
As a workaround I can use it if I stretch the blank board to cover whole work area and transform it back. Color of that board is free.
Light grey color of the blank board  transformed furthest behind works nicely with "extra working area".

**Comment by bancika** [comment]
What about other colors? Grid lines? Would this work?

![image](https://user-images.githubusercontent.com/11462281/134067196-8d30ace5-9d50-4e34-ae2d-dea0362941b9.png)

**Comment by visuttaja** [comment]
Yes .That looks ok. My experience is that with grey starting point is possible to get most color combinations. It is overwhelmingly most unlimiting color to build on functional color schemes. If the grey is quite light at the point where it is just starting to turn little dark it takes a lot of work away and lets ideas evolve many times so that color appears not to be limiting factor. I have spend hundreds of hours to fiddle with these and now I always start with grey. An example of an additional arbitrary advantage of such grey background is that it does not suck all the ink from printer which black background would do in accidental situation.

**Comment by bancika** [comment]
![image](https://user-images.githubusercontent.com/11462281/134135937-fd57d6a1-8445-4201-ae78-936649389ce2.png)

Played with the colors a bit and liking this combo

**Comment by visuttaja** [comment]
That is very good grid.  Rare gem i would say.  I could stare that combination 16 hours which is how things usually turn out when interface allows it.

**Comment by bancika** [comment]
This will be released in 4.21
