### ISSUE TITLE
How to move labels?

### ISSUE THREAD

**Issue by MarsManiac** [bancika/diy-layout-creator#674]
On many components I see a "Moveable label" checkbox but when I uncheck that box I still cannot move any labels.  I've tried many different key combinations (macOS 11.2) but I haven't been able to move any labels or even change there alignment.

Am I doing something wrong?  Is this even a bug?  

Thanks again!

**Comment by bancika** [comment]
You should see a green dot appearing when you select "Moveable label", you can use it to drag the label around

![image](https://user-images.githubusercontent.com/11462281/146669510-26c9af20-750b-4e33-badf-fd2ef405c93a.png)
