### ISSUE TITLE
Menu/icon bar is too tall when Windows pins it to one side of the screen

### ISSUE THREAD

**Issue by stodge** [bancika/diy-layout-creator#678]
Version: 4.20.0

If I pin the application to one half of the screen (drag to edge of screen and let Windows 10 size it to fill half of the screen), the menu/icon bar is too tall. I expect it's caused by the link for buying a coffee being so long. It's not a big deal, but it looks a bit odd.

![image](https://user-images.githubusercontent.com/95512/142419618-f4d12fb9-526f-45f1-8c1e-430b50924a9f.png)

**Comment by bancika** [comment]
Hopefully fixed for the next release
