### ISSUE TITLE
Delete on MacBook (UI enhancement)

### ISSUE THREAD

**Issue by overhumanalien** [bancika/diy-layout-creator#681]
Not a bug per se but a UI/UX enhancement request

Macbooks don't have a delete key. One can press fn+Backspc to delete, whick unfortunately is a two hand operation. Most programs have the backspace key mapped to perform delete operations. I would suggest to do the same in DIYLC too. Obviously backspace is needed too when editing text.

**Comment by bancika** [comment]
Fixed for 4.21
