### ISSUE TITLE
Suggestion: add keyboard shortcuts for toggling layer visibility

### ISSUE THREAD

**Issue by anttiope** [bancika/diy-layout-creator#693]
Running 4.22.0

Greetings from Finland and thank you for developing DIYLC. My experience is only a couple of hours working on stripboards with DIYLC, but I really like it. 

I suggest adding keyboard shortcuts for toggling layer visibility, for example: 
Ctrl+1 - toggle Chassis layer visibility
Ctrl+2 - toggle Board layer visibility
Ctrl+3 - toggle Wiring layer visibility
Ctrl+4 - toggle Component layer visibility
Ctrl+5 - toggle Wiring layer visibility
Ctrl+6 - toggle Text layer visibility

I find toggling layers really useful when working with stripboard due to cut traces and wiring, for example.

Have a great week!

-Antti

**Comment by bancika** [comment]
Done for 4.34
