### ISSUE TITLE
Two layers named Wiring

### ISSUE THREAD

**Issue by anttiope** [bancika/diy-layout-creator#694]
Running 4.22.0

There are two layers named Wiring. Should one of them be the Trace layer, perhaps Layer #3 between Board and Component layers? The manual refers to a Trace layer.

![image](https://user-images.githubusercontent.com/38606123/156615571-89342ca5-7bdf-4cb8-bee4-c0008ba9e56b.png)

Have a great week!

-Antti

**Comment by bancika** [comment]
Yes, it's a display issue. The bottom one should say Trace...the top one is
the new one.

**Comment by bancika** [comment]
Fixed
