### ISSUE TITLE
diylc-4.22.2 Java Virtual Machine Launcher error

### ISSUE THREAD

**Issue by blackcorvo** [bancika/diy-layout-creator#698]
I just downloaded the latest .zip version of the software, and trying to run the .exe file results in the following error:

![image](https://user-images.githubusercontent.com/29687112/160670451-5cb23c60-98cd-45ad-a0b7-e613c857362a.png)

It still opens if you run the .jar file, so it seems like an issue specifically with the executable. And the older 4.20.0 .zip I have here runs completely fine, so it's not an incompatibility with my system.

**Comment by blackcorvo** [comment]
After messing with the files a bit, I noticed that copying the 4.20.0 .ini file to the new version's folder made the program run normally.
Opening both .ini files on notepad revealed that removing the highlighted code from the 4.22.2 .ini allows the application to initiate properly. This code is not present in the 4.20.0 .ini file.
![image](https://user-images.githubusercontent.com/29687112/161120026-64c1196e-b617-45cc-ac24-f56a056c5aa3.png)
Not sure if it's some test code that was left over by accident, I don't know Java, but I'll be running it with the code removed for now.

**Comment by bancika** [comment]
Thanks for reporting!

**Comment by bancika** [comment]
Fixed
