### ISSUE TITLE
REQ new BJT pinouts ECB / BCE

### ISSUE THREAD

**Issue by abie-mixxx** [bancika/diy-layout-creator#708]
The new pinouts have been very helpful – tonight I noticed that the BJT pinouts are only CBE and EBC, but I have a number of transistors that are BCE / ECB. I couldn't find a way to make a new pinout so I am posting here. Thanks!

**Comment by bancika** [comment]
Added for next version

**Comment by abie-mixxx** [comment]
Awesome, thank you!

**Comment by abie-mixxx** [comment]
Thanks again – I also just signed up for a monthly donation, I've been
meaning to do that because I love the program so much and this was a good
reminder. I am super grateful for everything it has allowed me to learn and
do.

**Comment by bancika** [comment]
Awesome,  thanks so much!

**Comment by underwoodblog** [comment]
Found the BCE but how do I get a ECB?
