### ISSUE TITLE
File doesn't open with V4.22.2 to present. The last compatible version is V4.22.1

### ISSUE THREAD

**Issue by JRabbit54** [bancika/diy-layout-creator#712]
One particular file will not open with any version of the app newer than V4.22.1. The garbage collector runs red and the app hangs. Other more complicated files work fine up to the latest version 4.24.0. I cannot figure out why this one file hangs. 
Any suggestions?

[log-2022-06-26 04.33.38.txt](https://github.com/bancika/diy-layout-creator/files/8995626/log-2022-06-26.04.33.38.txt)

**Comment by bancika** [comment]
Please email problematic files to bancika at gmail.com and I'll debug the
issue

Tnx

**Comment by bancika** [comment]
Please try disabling Cache Boost in the config menu.

The sheer size and number of components overflows memory and it dies when
caching is enabled. I'll have to rethink caching strategy, I didn't have a
project this big when testing.

Let's keep this open until I figure out a way for caching to work on large
projects.

Cheers

**Comment by JRabbit54** [comment]
Hi Bane,

 

Disabling Cache Boost works fine on my system also. I’m not sure if I turned it on or if it is enabled by default.

 

Here is another file which is even larger than the one I sent you. It is a 30 watt version of the amp with even more components, plus it includes imported .jpg images of the transformers. It has more components and the overall complexity is higher than the first one I sent you (Interim.diy), yet it opens with cache boost enabled, on all versions of diy-layout-creator. I hope this help pin down the underlying issue.

 

Jack

**Comment by bancika** [comment]
Please send it to my email, attachments don't show up on github page.

Thanks

**Comment by bancika** [comment]
Figured it out, the patch will come out soon.
