### ISSUE TITLE
4 band Resistor Orange color

### ISSUE THREAD

**Issue by EL34xyz** [bancika/diy-layout-creator#714]
On 4 band 1/2 watt resistors (4th band is tolerance and not shown)
Can you make the Orange band Orangier?
The Orange is so close to Yellow that unless I display the value, it's hard for me to tell if the 3rd band is Orange or Yellow?

It's easier to tell if you put a 10k right next to a 100k
Then you can see a slight color difference
But a stand alone 10k can get mistaken for 100k because it looks closer to yellow than a deep orange

![resistor](https://user-images.githubusercontent.com/16766383/177179891-a7258ef4-04a6-4699-8532-b2403b33ad27.png)

**Comment by bancika** [comment]
Okay, that's easy enough...

![image](https://user-images.githubusercontent.com/11462281/177199366-33d04c89-64f4-4b24-94c4-e046aa69263c.png)

**Comment by EL34xyz** [comment]
Thanks Bane
