### ISSUE TITLE
DPDT (Center On) switch (On/On/On) request

### ISSUE THREAD

**Issue by PenBach** [bancika/diy-layout-creator#715]
Any chance we could get a DPDT (Center On) switch in DIYLC?

I'm sure you know what they are, but just to make sure we're talking about the same thing:
They are also called DPDT On/On/On.
Preferably "Type 1", but obviously if you could also add "Type 2" at the same time, that would be fantastic.
When viewed from below
"Type 1" - when in the center position, the middle/common terminals connect to the top left and bottom right terminals.
"Type 2" - when in the center position, the middle/common terminals connect to the bottom left and top right terminals.
Thanks.

**Comment by bancika** [comment]
Done for 4.26

**Comment by PenBach** [comment]
Thank you so much for this. Superb fast response. Much appreciated.
