### ISSUE TITLE
New Version Won't Start On Windows 10

### ISSUE THREAD

**Issue by drizztguen77** [bancika/diy-layout-creator#732]
After installing this latest version, 4.30.0, the program will not start. It displays the splash screen and then just hangs and never starts. I have to go into task manager and kill the Java process in order to stop it.

[log-2022-10-22 05.23.52.txt](https://github.com/bancika/diy-layout-creator/files/9845441/log-2022-10-22.05.23.52.txt)

**Comment by timsavage** [comment]
Have the same issue on linux

The [guava-31.1-jre.jar](https://github.com/bancika/diy-layout-creator/blob/master/diylc/diylc-core/lib/guava-31.1-jre.jar) is missing from the release package.

**Comment by bancika** [comment]
Fixed in 4.30.1, thanks!
