### ISSUE TITLE
IzPack hardcoded path in diylc-swing/build.xml

### ISSUE THREAD

**Issue by fpfaffendorf** [bancika/diy-layout-creator#744]
When building the project I've found that the hardcoded IzPack path in the build.xml (diylc-swing project) wasn't right for my setup. 
I'm leaving this issue here for anyone having the same issue.

Steps for solving the problem are:

- Download the IzPack installer if you don't have it already. http://izpack.org/downloads/ 
- Copy the IzPack path shown during the setup (WIN default is C:\Program Files (x86)\IzPack)
- Edit the build.xml file and change the hardcoded "e:\bane\dev\IzPack" to your path.

This is the path that works for me after doing the steps above (WIN).
<property name="izpack-dist" value="C:\Program Files (x86)\IzPack" />

**Comment by bancika** [comment]
Thanks, I'll include izPack in the version control.
