### ISSUE TITLE
"Schematic Symbol: Fuse" causing slow performance and graphical glitches

### ISSUE THREAD

**Issue by ctimlock** [bancika/diy-layout-creator#750]
Adding a Fuse symbol to a project causes extremely slow performance, and prevents the new project hierarchy from displaying. Additionally, rotating the symbol appears to intesify the errors.

To recreate:

1. Open a blank DIYLC project
2. Add a Fuse Schematic Symbol by dragging into grid
3. Observe a reduction in performance
4. Rotate the symbol by moving a control point
5. Observe even further reduction in performance

Log file and example project that contains only a fuse symbol attached.

[log-2023-01-09 11.25.55.txt](https://github.com/bancika/diy-layout-creator/files/10373129/log-2023-01-09.11.25.55.txt)
[fuseTest.zip](https://github.com/bancika/diy-layout-creator/files/10373131/fuseTest.zip)

**Comment by bancika** [comment]
Fixed for 4.36
