### ISSUE TITLE
losing ability to select things after placing a fuse schematic symbol

### ISSUE THREAD

**Issue by blackcorvo** [bancika/diy-layout-creator#754]
I'm having this bug whenever I try to place a fuse on the work area. It doesn't let me select anything and doesn't even show the selection square anymore. Running v4.35.0 on Windows 10. I can still Ctlr+Z to remove the placed fuse, and it takes a second to register.

It also happens if you place a fuse in a brand new project.

Video of the bug in action:
https://www.youtube.com/watch?v=PoXDxu7HvCk

**Comment by bancika** [comment]
Fixed for 4.36
