### ISSUE TITLE
request for help/info

### ISSUE THREAD

**Issue by JunkMcNuggets** [bancika/diy-layout-creator#755]
hello. first off, please forgive me if I'm going about this all wrong. after using DIYLC for probably 3+ years, and by extension GitHub, i still know tantamount to zero percent pertaining to GitHub. 

I just recently noticed the curve tracer part of the program, which seriously floated my nerd boat. i easily found out how tp add a curve and change its shape via little  green dots, etc. mainly the couple very clearly labeled east to achieve tasks. but my question is how would one actually edit the axis (axes?)?  I've tried right-clicking, double-clicking, cursing loudly at my laptop, and even leaving a nasty surprise in my neighbor's mailbox while chanting my unfaltering service to The Dark One, all to no avail.

For example, BJTs and JFETs are both available to use in the layout creator, and being a lover of the latter just as much as the former, I wanted to change the Y-axis to something more akin you'd find on say a J113's datasheet. This is a very specific example of course, it could require changing either axis to anything. 

**Again, please forgive my naivete as well as my overall ignorance on the norms of GitHub entirely**. It is not for a lack of trying nor effort and research nor many hours spent attempting to gain a better grasp on all of this. I'm just not that type of computer dude. that being said, **I motherf#$ing LOVE DIYLC**! And I love everyone who made this happen, is still making it happen, and allows it to be freely available and accessible to all the Cro-Magnon schmucks like me who just love to play music and make their own shit to do it with. And also, if you somehow are actually my real-life neighbor, I was _obvi totes jk_ about your mailbox. But I did see _shady Greg with that mole from the house on the other side of yours_, acting really _sus_ the other day around there, and he definitely seems off-kilter. 

Thank you for your time. You can now all get the hell out of my yard... OOPS!   Sorry.

**Comment by bancika** [comment]
is this what you mean? Axis configuration is in the bottom of the screen

![image](https://user-images.githubusercontent.com/11462281/227773834-404791d8-102f-4606-a703-e7c881d270d6.png)
