### ISSUE TITLE
Transistor TO-126 can't be rotated

### ISSUE THREAD

**Issue by tyrel** [bancika/diy-layout-creator#758]
DIYLC v4.35.0. Noticed that Transistor (TO-126) cannot be rotated, but other components can be. It's kind of a pain!

**Comment by bancika** [comment]
Can you try double click and change orientation from there?

**Comment by tyrel** [comment]
Oh yes, that does work. But if I try to rotate it with Alt+Left Arrow or Alt+Right Arrow, I get "Selection contains components that cannot be rotated. Do you want to exclude them?"

**Comment by bancika** [comment]
Yes, that happens for some components. I'm working on that

**Comment by tyrel** [comment]
Great, thanks for your hard work!
