### ISSUE TITLE
Lever Switch - Super Switch not looking right after v4.29 ; <orientation> lost

### ISSUE THREAD

**Issue by PenBach** [bancika/diy-layout-creator#762]
Issue upgrading to v4.35 from v4.29.0

I briefly mentioned this in another thread, but thought it deserved to be separate, and I can now give some more information after investigating it a bit.
When I opened (in  v4.35) the last layout that I worked on (in v4.29), the Lever Switch - Super Switch was not as it should be. Not sure if there was anything else out of place; that's the one that lept out as being wrong.

I wonder if it is because of this in v4.30:
"[New Feature] Ability to rotate 'Lever Switch' and 'Schaller Megaswitch' by any angle"

I haven't got any complex drawings so I can't check other things.
Hopefully it's only the Lever Switch that has a problem and it can be easily fixed so that old drawings can be opened in newer versions without problems.

I've added a simple drawing showing the issue and screenshots.
As you can see, the v4.35 version has the body and tags displaced from each other.
![DIYLC_Test_Switches_v429_v435](https://user-images.githubusercontent.com/108829803/225102344-e5dfe134-4556-43ee-9be4-1ffd42b5dc0f.JPG)
[Test_Switches_v429_v435.zip](https://github.com/bancika/diy-layout-creator/files/10972322/Test_Switches_v429_v435.zip)

The v4.29 .diy file has this line
`      <orientation>_180</orientation>`
which is not carried into subsequent versions
and the v4.35 save of that file has this line instead
`      <angle>0</angle>`
so the `<orientation>` has been lost.

**Comment by bancika** [comment]
Fixed for 4.36
