### ISSUE TITLE
Feature Request: proper name copy of component

### ISSUE THREAD

**Issue by leonllrmc** [bancika/diy-layout-creator#772]
Good Morning,

A feature that would greatly improve workflow with DIYLC would be that,
If you copy a component with a **custom name**, Ex: a LED named _LED1_, that when you copy and paste the component,
instead of renaming it to _D1_, it would continue by placing _LED2_ as the name, instead of discarding it,
It would save a ton of time when you have a lot of components with custom names to place

Best regards and hope to see your response soon

**Comment by bancika** [comment]
There's already option for that called renumber on paste
