### ISSUE TITLE
Component request: Buzzer symbol

### ISSUE THREAD

**Issue by greenonline** [bancika/diy-layout-creator#780]
Is it possible to add a buzzer symbol? Either active, or passive, or both. Variable size.

I am currently using the "Electro-Mechanical>Fuse Holder (Panel)" symbol to represent a Buzzer.

**Comment by M0JXD** [comment]
Hi,

I'm working on a Buzzer schematic symbol. After re-reading this I'm unsure if your request is for a schematic symbol or the component?

I've noticed a few different buzzer types, e.g. these ones "flying lead" and mounting holes as well as PCB mount ones.

![9446bf54-ffad-4ac3-a905-f43b60614a3c_1 c481cb972065f7989a5f1e43a482a3fe-877912955](https://github.com/user-attachments/assets/bb7ebecf-e32f-490a-a25d-fc5931669a23)
![buzzer-en-general-in-416-26-B-3794026034](https://github.com/user-attachments/assets/a080b497-a38a-4a7f-a612-ed0ca41bcdb5)

In terms of schematic symbols it seems both orientations of the semi-circle are acceptable.

![Electrical-symbol-buzzer_wucyg5-3983455612](https://github.com/user-attachments/assets/dcf8e062-fcaf-450b-a3d8-a9374d8ad5f8)
![buzzersymbol](https://github.com/user-attachments/assets/f1a44c54-0364-4d3a-b253-a4516f3cd2d3)


For now I will do the schematic symbol, I can add the semi-circle orientation as an option/variant for each of the symbols if that is desired, although the first one seems the most common.

I'll do the PCB mount component after. Is there any desire for the version with mounting holes/flying leads? If so I can add places for flying leads to go akin to how the pickups are done.

If a datasheet of the exact part you want is available that'd be a big help! :)

**Comment by greenonline** [comment]
I was after a component symbol for the stripboard layout, rather than a schematic symbol. The type of buzzer that I had in mind was the non-flying lead type, as in your second photo. 

I don't have a specific buzzer in mind, and so I don't actually know the buzzer's diameter nor the pin spacing, that is why I asked if it could be of variable diameter and pin separation.

As a general idea, like I mentioned above, I was using the *fuse holder* component symbol (for the strip board layout), which gives an approximate layout shape. You can see what I mean here: https://github.com/greenonline/AVR_High_Voltage_Fuse_Programmer_Enhanced/blob/main/README.md

**Comment by M0JXD** [comment]
OK, I think I understand. I could base it on the radial electrolytic cap? That has a settable diameter and would also allow for any lead length.

It seems the active/passive tend to look the same. By default I'll make it 12mm like the ones in these links, they seem the most popular.

https://www.aliexpress.com/item/1005006213298069.html?utparam-url=scene%3Asearch%7Cquery_from%3A
https://www.aliexpress.com/item/1005006626224138.html?utparam-url=scene%3Asearch%7Cquery_from%3A
