### ISSUE TITLE
UX enhancement: Have grid numbers/letters on both sides of vero board (stripboard)

### ISSUE THREAD

**Issue by greenonline** [bancika/diy-layout-creator#782]
It would be useful to have the grid markings on both sides of the Vero board (stripboard) - maybe make it switchable option. 

For very large boards, or for designing on smaller screens, this would prevent having to continually scroll back up to the top/left to see what the row letter or column number is, when working on the right hand side or bottom of the board (when the top or left is off screen).

Currently, v4.37 the grid is not marked along the bottom or right of the stripboard.

**Comment by bancika** [comment]
already there

![image](https://github.com/bancika/diy-layout-creator/assets/11462281/2d9c87ed-781c-4700-a3fa-ce8d3c69ed83)
