### ISSUE TITLE
Toroidal Inductor Performance Issue

### ISSUE THREAD

**Issue by Geferg** [bancika/diy-layout-creator#810]
### Description
Adding the component `Toroidal Inductor` under category `Passive` makes the program unresponsive. With this component present, moving any component, adding components and so on does not show changes or has an unpredictable behavior. After moving something, changes only show after selecting something else from the components list (e.g. a resistor, or a folder), as if something is being blocked by having the grid with the `Toroidal Inductor` focused. There are other issues happening but the root cause is probably the same for all of it so i don't feel the need to list more symptoms.

### Steps to reproduce
1. Create a new project
2. Add the `Toroidal Inductor` to the grid
3. Add any new component to the grid
4. Move any connection node of the already placed components

### Log
After following the steps to reproduce, this is my log.
[log-2024-02-21 02.45.43.txt](https://github.com/bancika/diy-layout-creator/files/14360244/log-2024-02-21.02.45.43.txt)

### Other
- diy-lc version: 4.37.0
- OS: windows 11

Let me know if there are any other details i can provide that would be helpful for resolving this.

**Comment by bancika** [comment]
should be fixed now
