### ISSUE TITLE
Defender complains about diylc-4.37.0-win.exe

### ISSUE THREAD

**Issue by ghollf** [bancika/diy-layout-creator#822]
Windows Defender complains on download and start of [diylc-4.37.0-win.exe](https://github.com/bancika/diy-layout-creator/releases/download/v4.37.0/diylc-4.37.0-win.exe).

Content opened with 7-zip also looks strange!?
<img width="298" alt="Screenshot 2024-05-19 091446" src="https://github.com/bancika/diy-layout-creator/assets/38644565/ddd324d4-f217-46e9-bb3c-f31cddd432f2">

**Comment by bancika** [comment]
It complains because I publish it as an individual without a certificate
but it's 100% safe as long as you download it from this website. I use it
myself too :)
