### ISSUE TITLE
Update to a modern Big Sur style icon on Mac

### ISSUE THREAD

**Issue by jamesdlow** [bancika/diy-layout-creator#824]
The current DIYLC icon doesn't match the new design of icons since OSX BigSur. It should be slightly smaller, have a 22% border radius, and have a slight shadow. I've done a version of this icon (see attached zip), though it would be better if someone edited the original Photoshop file to be in this style.

[diylcicon.zip](https://github.com/user-attachments/files/15781023/diylcicon.zip)

**Comment by bancika** [comment]
thank you for the contribution, I will include it in the next release
