### ISSUE TITLE
Crashy design...

### ISSUE THREAD

**Issue by ajawamnet** [bancika/diy-layout-creator#826]
For some reason the attached design just hangs on my install... new documents seem OK.  It seems like it was when I put a link to an image file in the design...
[diy1.zip](https://github.com/user-attachments/files/15812461/diy1.zip)

**Comment by ajawamnet** [comment]
I think it's the toroidal inductor that's causing the issue. See vid

https://github.com/bancika/diy-layout-creator/assets/25396864/11d11a92-1af5-4247-acd5-483e465855bb

**Comment by bancika** [comment]
Fixed for the next version. As a workaround just set the value for inductance and it will work fine (double click on the component and edit)
