### ISSUE TITLE
Can't get fresh install to run on Ubuntu

### ISSUE THREAD

**Issue by moscfet** [bancika/diy-layout-creator#835]
I'm using Ubuntu 20.04, Kernel 6.2. I've tried the following command, 

#export DISPLAY=:0.0

I've tried reinstalling the flatpak through terminal manually but I get the same result. 

17:26:38,953 ERROR [main] DIYLCStarter - Major error while starting DIYLC
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)

**Comment by M0JXD** [comment]
What display server are you using; X11 or Wayland? I'm currently on Mint which only uses X11 but I think Ubuntu offers both?

There are known permissions issues with the Flatpak version, I use the universal release instead. Download the zip, extract it, run a chmod on run.sh and then ./run.sh

https://github.com/bancika/diy-layout-creator/releases/tag/v4.37.0

**Comment by moscfet** [comment]
That’s what I ended up doing and it’s working fine now. Thanks for getting back to me.
