### ISSUE TITLE
Potential Bug: Analyze Guitar Diagrams Ignoring Pot Output on Switch

### ISSUE THREAD

**Issue by StateOfEpicicity** [bancika/diy-layout-creator#842]
Here is a weird one: The Analyze Guitar Diagram command won't recognize the pot output if it's connected to a blade switch first.  I was working on a weird wiring layout and discovered this, so I've simplified this to illustrate the potential bug.  Thanks in advance for looking into it!
[Ignoring Pot Output on Switch.zip](https://github.com/user-attachments/files/17687892/Ignoring.Pot.Output.on.Switch.zip)
[log-2024-11-09 08.00.21.txt](https://github.com/user-attachments/files/17687895/log-2024-11-09.08.00.21.txt)

**Comment by StateOfEpicicity** [comment]
[log-2024-11-09 08.00.21.txt](https://github.com/user-attachments/files/17687894/log-2024-11-09.08.00.21.txt)

**Comment by bancika** [comment]
same underlying issue as #846
