### ISSUE TITLE
TO220 Transistor drawing sucks - can't tell what side the heat sink is

### ISSUE THREAD

**Issue by php4fan** [bancika/diy-layout-creator#848]
I placed this into my circuit:

![image](https://github.com/user-attachments/assets/b94ef148-e3ed-43e0-aa55-0917ef614ee8)

This is what it looks like:
![image](https://github.com/user-attachments/assets/4f67e07a-b344-497a-a04f-69f6cab772f1)

It's quite annoying that you can't tell on which side the heat sink is (left or right in the example above). The only workaround is to display the pinout, which will at least indirectly tell me what the orientation is.

It would be nicer if it looked something like this:

![image](https://github.com/user-attachments/assets/9d03e590-6094-42b1-a9ec-57e77303b9d9)

**Comment by bancika** [comment]
While I do appreciate reporting any issues with the app, titles like this are not cool. DIYLC is totally free and you are getting your money's worth and then some. 

That said, this is what TO220 looks like when placed

<img width="412" alt="Screenshot 2024-12-16 at 10 35 49" src="https://github.com/user-attachments/assets/f9ee3c9b-c1ec-41ac-b534-ed95d1dc9091" />

there must be something else that's causing the tab not to be rendered. Try to double click on the transistor and take a screenshot of the details screen to see if there's any property that is misconfigured. Also, upload the log from the time the issue happens, maybe there's some clue there
